const { execSync } = require('child_process');

const issues = [
  // 1-10: Backend Refactoring & Architecture
  { title: "Backend: Migrate authentication service to TypeScript", body: "Migrate the core auth.service.js to TypeScript, adding strict interfaces for user payloads, JWT generation, and error handling. This will improve type safety across the backend. Expected changes: ~100-200 lines.", labels: "ECSoC26,backend,enhancement" },
  { title: "Backend: Implement Redis caching layer for reports", body: "Heavy reporting endpoints take too long. Implement a Redis caching middleware to cache the results of complex MongoDB aggregations in the reports controller for at least 15 minutes. Expected changes: ~80-120 lines.", labels: "ECSoC26,backend,performance" },
  { title: "Backend: Implement structured logging using Winston", body: "Replace all console.log statements with a centralized Winston logger configuration. It should support log rotation, different log levels (info, warn, error), and JSON formatting for production. Expected changes: ~100-150 lines.", labels: "ECSoC26,backend,enhancement" },
  { title: "Backend: Build an Audit Trail / Activity Logging System", body: "Create a new Mongoose model for AuditLogs and a middleware to automatically intercept and log all write/update/delete operations on sensitive resources (like Payrolls and Employees) to the database. Expected changes: ~150-250 lines.", labels: "ECSoC26,backend,security" },
  { title: "Backend: Implement JWT Refresh Token Rotation", body: "Enhance the authentication system by implementing short-lived access tokens and secure, HTTP-only refresh tokens. Build endpoints for token refreshing and revoking. Expected changes: ~150-250 lines.", labels: "ECSoC26,backend,security" },
  { title: "Backend: Add BullMQ for background email processing", body: "Currently, emails are sent synchronously, slowing down API responses. Integrate BullMQ with Redis to process all email sending (e.g., welcome emails, payroll notifications) in background worker threads. Expected changes: ~150-200 lines.", labels: "ECSoC26,backend,performance" },
  { title: "Backend: Implement comprehensive API input sanitization", body: "Add a robust sanitization middleware using a library like DOMPurify or custom regex to strip XSS vectors from all incoming JSON payloads and URL parameters before they hit controllers. Expected changes: ~100-150 lines.", labels: "ECSoC26,backend,security" },
  { title: "Backend: Create a database seeding script for development", body: "Write a comprehensive database seeder script using faker.js that generates 500+ realistic employees, departments, and payroll records to assist with local development and testing. Expected changes: ~150-300 lines.", labels: "ECSoC26,backend,enhancement" },
  { title: "Backend: Migrate Mongoose schemas to use strict validation", body: "Update all Mongoose schemas (Employee, Payroll, User) to use advanced validation rules (custom validators, enum checks, regex for emails/phones) directly at the database level. Expected changes: ~100-200 lines.", labels: "ECSoC26,backend,enhancement" },
  { title: "Backend: Implement centralized error handling middleware", body: "Refactor the Express app to use a centralized error handling middleware class that catches all async errors, formats them consistently (standard API error response), and logs them appropriately. Expected changes: ~80-120 lines.", labels: "ECSoC26,backend,enhancement" },

  // 11-20: Frontend Architecture & Refactoring
  { title: "Frontend: Migrate state management from Redux to Zustand", body: "Redux is adding too much boilerplate. Refactor the global state management (user sessions, UI themes) to use Zustand. This involves rewriting actions, reducers, and updating all connected components. Expected changes: ~200-300 lines.", labels: "ECSoC26,frontend,enhancement" },
  { title: "Frontend: Build a custom, accessible Modal/Dialog component", body: "Replace all ad-hoc or third-party modals with a highly reusable, accessible custom Modal component. It must support focus trapping, keyboard navigation (Escape to close), and dynamic rendering via Portals. Expected changes: ~150-200 lines.", labels: "ECSoC26,frontend,enhancement" },
  { title: "Frontend: Implement comprehensive Formik & Yup validation", body: "Refactor the Add/Edit Employee forms to use Formik for form state management and Yup for strict client-side validation schema. Display proper inline error messages. Expected changes: ~150-250 lines.", labels: "ECSoC26,frontend,enhancement" },
  { title: "Frontend: Add Virtualized Lists for large data tables", body: "The Employee and Payroll tables freeze the browser when loading 1000+ rows. Implement react-window or react-virtualized to render only the visible rows in the DOM. Expected changes: ~100-200 lines.", labels: "ECSoC26,frontend,performance" },
  { title: "Frontend: Build a custom Toast Notification system", body: "Build a custom, globally accessible Toast/Snackbar notification context and provider from scratch (removing external dependencies like react-toastify). It must support stacking and auto-dismiss. Expected changes: ~150-200 lines.", labels: "ECSoC26,frontend,enhancement" },
  { title: "Frontend: Implement internationalization (i18n) support", body: "Set up react-i18next and extract all hardcoded strings in the Dashboard, Sidebar, and Settings pages into translation JSON files for English and Spanish. Expected changes: ~200-400 lines.", labels: "ECSoC26,frontend,enhancement" },
  { title: "Frontend: Add a Dark Mode toggle context and system", body: "Implement a robust Dark Mode context that persists user preference in localStorage and applies Tailwind dark classes globally. Refactor at least 5 major components to fully support dark mode colors. Expected changes: ~100-200 lines.", labels: "ECSoC26,frontend,enhancement" },
  { title: "Frontend: Implement drag-and-drop file upload for avatars", body: "Build a custom drag-and-drop zone component for uploading employee profile pictures. It should include client-side image resizing, preview generation, and progress indicators. Expected changes: ~150-250 lines.", labels: "ECSoC26,frontend,enhancement" },
  { title: "Frontend: Create a robust pagination component", body: "Build a reusable pagination component from scratch that handles edge cases (e.g., hiding page numbers when there are >10 pages, prev/next buttons) and integrate it with the Reports tables. Expected changes: ~100-150 lines.", labels: "ECSoC26,frontend,enhancement" },
  { title: "Frontend: Refactor API calls to use Axios interceptors", body: "Centralize all fetch/API calls by creating an Axios instance with interceptors that automatically attach JWT tokens and handle 401 Unauthorized responses (redirect to login). Expected changes: ~100-150 lines.", labels: "ECSoC26,frontend,enhancement" },

  // 21-30: Testing (Frontend & Backend)
  { title: "QA: Add unit tests for Employee Service logic", body: "Write comprehensive unit tests for `employee.service.js` using Jest. You must mock the Mongoose models and test all CRUD operations, including failure scenarios. Expected changes: ~150-300 lines.", labels: "ECSoC26,backend,good-pr" },
  { title: "QA: Add unit tests for Payroll Calculation Service", body: "The payroll calculation logic is highly complex. Write robust unit tests verifying exact tax calculations, gross-to-net logic, and deduction edge cases using Jest. Expected changes: ~200-400 lines.", labels: "ECSoC26,backend,good-pr" },
  { title: "QA: Implement React Testing Library for Dashboard", body: "Write integration tests for the main Dashboard component using React Testing Library. Mock the API responses and verify that charts and metrics render correctly. Expected changes: ~150-250 lines.", labels: "ECSoC26,frontend,good-pr" },
  { title: "QA: Implement React Testing Library for Forms", body: "Write tests for the Add Employee form. Simulate user typing, form validation errors, and submit button clicks to ensure the UI behaves as expected. Expected changes: ~150-200 lines.", labels: "ECSoC26,frontend,good-pr" },
  { title: "QA: Setup Cypress E2E tests for User Authentication", body: "Configure Cypress and write End-to-End tests simulating a user signing up, logging in, handling incorrect passwords, and logging out successfully. Expected changes: ~100-200 lines.", labels: "ECSoC26,frontend,good-pr" },
  { title: "QA: Integration tests for PDF Generation API", body: "Write Supertest integration tests specifically for the PDF report generation endpoints. Verify that the correct headers are set and a valid binary stream is returned. Expected changes: ~100-150 lines.", labels: "ECSoC26,backend,good-pr" },
  { title: "QA: API Contract Testing with Supertest", body: "Write Supertest suites for the entire User and Auth router, asserting HTTP status codes, JSON structures, and error messages for all endpoints. Expected changes: ~200-400 lines.", labels: "ECSoC26,backend,good-pr" },
  { title: "QA: Add performance benchmark tests using Autocannon", body: "Write a script using `autocannon` to benchmark the performance of the heaviest API endpoints (like generating payrolls) and output a markdown report locally. Expected changes: ~100-150 lines.", labels: "ECSoC26,backend,performance" },
  { title: "QA: Write visual regression tests using Playwright", body: "Configure Playwright to take screenshots of the 5 main pages (Dashboard, Reports, Employees, Settings, Login) and compare them against baseline images to prevent CSS regressions. Expected changes: ~100-200 lines.", labels: "ECSoC26,frontend,good-pr" },
  { title: "QA: Setup Mutation Testing with Stryker", body: "Configure Stryker to run mutation tests against the backend utility functions (e.g., tax calculation, date formatting) to ensure our Jest tests are actually effective. Expected changes: ~50-100 lines.", labels: "ECSoC26,backend,good-pr" },

  // 31-40: New Features & Enhancements
  { title: "Feature: Build an Advanced Custom Report Builder UI", body: "Create a new interface allowing admins to build custom reports by selecting specific columns (Name, Salary, Tax, Date), adding filters, and saving the preset to the database. Expected changes: ~300-500 lines.", labels: "ECSoC26,frontend,enhancement" },
  { title: "Feature: Implement Multi-factor Authentication (MFA)", body: "Allow users to enable MFA using Google Authenticator (TOTP). Build the backend logic to generate a secret, verify the token, and the frontend UI to display the QR code. Expected changes: ~200-400 lines.", labels: "ECSoC26,backend,security" },
  { title: "Feature: Implement OAuth2 Login (Google / GitHub)", body: "Add \"Sign in with Google\" and \"Sign in with GitHub\" buttons using Passport.js. Create the necessary backend routes and handle the callback redirects. Expected changes: ~150-300 lines.", labels: "ECSoC26,backend,enhancement" },
  { title: "Feature: Build a Real-time Chat / Announcements Widget", body: "Integrate Socket.io to build a small chat/announcement widget where admins can broadcast messages to all logged-in employees in real time. Expected changes: ~200-300 lines.", labels: "ECSoC26,frontend,enhancement" },
  { title: "Feature: Add interactive Onboarding Tooltips", body: "Integrate a library like `react-joyride` or build a custom solution to guide new users through the app (Dashboard -> Add Employee -> Generate Payroll) step-by-step. Expected changes: ~150-250 lines.", labels: "ECSoC26,frontend,enhancement" },
  { title: "Feature: Implement CSV Bulk Import for Employees", body: "Build a frontend page with a file uploader that parses CSV files (using PapaParse) and sends a batch payload to a new backend endpoint for bulk inserting employees. Expected changes: ~200-350 lines.", labels: "ECSoC26,frontend,enhancement" },
  { title: "Feature: Comprehensive Dashboard Analytics widgets", body: "Add 4 new advanced charts to the dashboard: Employee Growth over Time (Line Chart), Salary Distribution (Histogram), Department Budgets (Pie Chart), and Attrition Rate. Expected changes: ~200-300 lines.", labels: "ECSoC26,frontend,enhancement" },
  { title: "Feature: Build a User Profile Settings Page", body: "Create a dedicated page where users can update their profile information, upload an avatar, change their password, and configure email notification preferences. Expected changes: ~150-250 lines.", labels: "ECSoC26,frontend,enhancement" },
  { title: "Feature: Soft Delete implementation for Mongoose", body: "Modify all core Mongoose schemas to support soft deletion (e.g., `isDeleted` flag). Refactor all GET requests to filter out soft-deleted records, and build an 'Archive' view in the frontend. Expected changes: ~200-300 lines.", labels: "ECSoC26,backend,enhancement" },
  { title: "Feature: Add Webhook integrations for external services", body: "Build a Webhooks module where users can register URLs. The backend should dispatch a POST payload to these URLs whenever a new Payroll is generated or an Employee is hired. Expected changes: ~200-300 lines.", labels: "ECSoC26,backend,enhancement" },

  // 41-50: Tooling, DX, and DevOps
  { title: "DevOps: Dockerize the entire application stack", body: "Write complex Dockerfiles for the frontend and backend. Create a `docker-compose.yml` that orchestrates the Node backend, Vite frontend, MongoDB database, and Redis cache for seamless local development. Expected changes: ~100-150 lines.", labels: "ECSoC26,cicd,enhancement" },
  { title: "CI/CD: Automate PR Labeling and Release Drafting", body: "Enhance GitHub Actions to automatically label PRs based on the paths modified (frontend/backend) and use release-drafter to automatically compile a changelog when PRs are merged. Expected changes: ~100-150 lines.", labels: "ECSoC26,cicd,enhancement" },
  { title: "Tooling: Configure Husky hooks and lint-staged", body: "Set up Husky pre-commit hooks to run `lint-staged`. Configure `lint-staged` to run ESLint, Prettier, and run relevant Jest tests on staged files before allowing a commit. Expected changes: ~50-100 lines.", labels: "ECSoC26,cicd,enhancement" },
  { title: "Tooling: Migrate Monorepo from npm to pnpm or Turborepo", body: "The current npm workspace setup is slow. Migrate the repository to use `pnpm` workspaces or `Turborepo` for faster dependency resolution and cached builds. Expected changes: ~150-200 lines.", labels: "ECSoC26,cicd,enhancement" },
  { title: "DevOps: Setup Prometheus and Grafana Monitoring", body: "Integrate `prom-client` in the Express backend to expose a `/metrics` endpoint. Provide configuration files for a local Prometheus scraper and a pre-built Grafana dashboard JSON. Expected changes: ~150-250 lines.", labels: "ECSoC26,backend,performance" },
  { title: "Frontend: Setup Storybook for component library", body: "Install and configure Storybook for the frontend. Write at least 5 stories for foundational UI components (Buttons, Inputs, Cards, Modals) to kickstart the design system documentation. Expected changes: ~200-300 lines.", labels: "ECSoC26,frontend,enhancement" },
  { title: "Backend: Generate OpenAPI / Swagger Documentation", body: "Integrate `swagger-ui-express` and write detailed JSDoc comments/OpenAPI definitions for the entire REST API so developers can explore endpoints interactively at `/api-docs`. Expected changes: ~300-500 lines.", labels: "ECSoC26,backend,documentation" },
  { title: "Frontend: Implement Service Worker for PWA Support", body: "Configure Vite-PWA to turn the application into a Progressive Web App. Implement caching strategies for static assets and offline fallback pages. Expected changes: ~100-150 lines.", labels: "ECSoC26,frontend,enhancement" },
  { title: "DevOps: Add automated dependency updates via Dependabot", body: "Create extensive configuration files for Dependabot/Renovate. Setup workflows to automatically auto-approve and merge minor/patch dependency bumps if the CI test suite passes. Expected changes: ~80-120 lines.", labels: "ECSoC26,cicd,enhancement" },
  { title: "DevOps: Configure Sentry for Production Error Tracking", body: "Integrate Sentry SDKs into both the React frontend and Node.js backend. Configure breadcrumbs, user context, and source maps uploading during the build process. Expected changes: ~100-150 lines.", labels: "ECSoC26,frontend,backend" }
];

console.log(`Starting to create ${issues.length} issues...`);

for (let i = 0; i < issues.length; i++) {
  const issue = issues[i];
  console.log(`[${i+1}/${issues.length}] Creating issue: ${issue.title}`);
  try {
    // Escape double quotes in body and title for the command line
    const title = issue.title.replace(/"/g, '\\"');
    const body = issue.body.replace(/"/g, '\\"');
    const cmd = `gh issue create --title "${title}" --body "${body}" --label "${issue.labels}"`;
    execSync(cmd, { stdio: 'ignore' });
  } catch (err) {
    console.error(`Failed to create issue: ${issue.title}`);
    console.error(err);
  }
}

console.log('Finished creating all issues!');
