/**
 * Cardiopulmonary ECMO & Advanced Mechanical Ventilation Data Models
 * Adheres to ELSO (Extracorporeal Life Support Organization) Guidelines,
 * ARDSNet Lung-Protective Mechanical Ventilation Standards, Berlin ARDS Definitions,
 * and FDA 21 CFR Part 11 Electronic Telemetry & Audit Integrity Standards.
 */

export const ECMO_CIRCUIT_MODES = {
  VV_ECMO: {
    id: 'VV_ECMO',
    name: 'Veno-Venous (VV) ECMO',
    primaryIndication: 'Severe Hypoxemic/Hypercapnic Respiratory Failure (ARDS / Status Asthmaticus)',
    cannulation: 'Femoral-Jugular or Dual-Lumen Avalon Cannula',
    supportType: 'Pure Pulmonary Gas Exchange',
    targetSvO2: [70, 85],
    targetFlowPerKgMin: [50, 80], // mL/kg/min
    sweepGasRatioDefault: 1.0, // 1:1 sweep gas to blood flow
  },
  VA_ECMO: {
    id: 'VA_ECMO',
    name: 'Veno-Arterial (VA) ECMO',
    primaryIndication: 'Refractory Cardiogenic Shock / Cardiac Arrest (E-CPR) / Post-Cardiotomy',
    cannulation: 'Femoral-Femoral or Central Aortic-Atrial Cannula with Distal Perfusion Catheter',
    supportType: 'Full Cardiopulmonary Biventricular & Respiratory Support',
    targetSvO2: [65, 75],
    targetFlowPerKgMin: [60, 100], // mL/kg/min
    sweepGasRatioDefault: 0.8,
  },
  VAV_ECMO: {
    id: 'VAV_ECMO',
    name: 'Veno-Arterio-Venous (VAV) Hybrid ECMO',
    primaryIndication: 'Harlequin / North-South Syndrome (Differential Hypoxemia with LV recovery)',
    cannulation: 'Femoral Drainage + Femoral & Right Internal Jugular Dual Reinfusion',
    supportType: 'Combined Hemodynamic & Upper Body Oxygenation Rescue',
    targetSvO2: [70, 80],
    targetFlowPerKgMin: [70, 110],
    sweepGasRatioDefault: 1.0,
  },
};

export const CIRCUIT_PRESSURE_THRESHOLDS = {
  P1_PRE_PUMP_DRAINAGE: {
    unit: 'mmHg',
    normalMin: -80,
    normalMax: -20,
    cautionNegative: -100,
    criticalNegative: -150, // Risk of cavitation, hemolysis, chattering/cannula kick
    description: 'Inlet drainage cannula pressure before centrifugal blood pump',
  },
  P2_PRE_OXYGENATOR: {
    unit: 'mmHg',
    normalMin: 120,
    normalMax: 260,
    cautionMax: 300,
    criticalMax: 380, // Excessive post-pump resistance or impending membrane clot
    description: 'High-pressure outlet of blood pump before polymethylpentene membrane',
  },
  P3_POST_OXYGENATOR: {
    unit: 'mmHg',
    normalMin: 90,
    normalMax: 220,
    cautionMax: 260,
    criticalMax: 320, // Reinfusion line kink or systemic vascular clamping
    description: 'Reinfusion cannula delivery pressure after membrane gas exchange',
  },
  TRANSMEMBRANE_PRESSURE_DELTA_P: {
    unit: 'mmHg',
    normalMin: 15,
    normalMax: 45,
    cautionMax: 50,
    criticalMax: 70, // Membrane lung thrombosis / fibrin matrix deposition
    description: 'Delta P (P2 - P3) across membrane oxygenator',
  },
};

export const LUNG_VENTILATION_SAFETY_TARGETS = {
  DRIVING_PRESSURE: {
    unit: 'cmH2O',
    targetMax: 14,
    criticalMax: 18,
    formula: 'Plateau Pressure (Pplat) - PEEP',
    clinicalSignificance: 'Independent predictor of ARDS barotrauma and mortality',
  },
  MECHANICAL_POWER: {
    unit: 'J/min',
    targetMax: 17,
    criticalMax: 24,
    formula: '0.098 * RR * Vt * (Ppeak - (DeltaP / 2))',
    clinicalSignificance: 'Cumulative energy load delivered to lung parenchyma per minute',
  },
  STATIC_COMPLIANCE: {
    unit: 'mL/cmH2O',
    normalMin: 50,
    severeARDSMin: 10,
    formula: 'Vt / (Pplat - PEEP)',
    clinicalSignificance: 'Elastic compliance of respiratory system',
  },
  REST_VENTILATOR_SETTINGS: {
    description: 'Lung-rest strategy during ECMO support to prevent VILI',
    targetVtPerKgPBW: [3, 4], // mL/kg Predicted Body Weight
    targetPEEP: [10, 14], // cmH2O
    targetFiO2: [0.30, 0.40], // Low FiO2 to reduce oxygen toxicity and absorption atelectasis
    targetRR: [6, 12], // Breaths per minute
    targetPplat: [20, 25], // cmH2O max
  },
};

export const ANTICOAGULATION_PROTOCOLS = {
  UNFRACTIONATED_HEPARIN: {
    id: 'UFH',
    name: 'Unfractionated Heparin (IV Infusion)',
    monitoringTarget: 'Anti-Factor Xa: 0.3 - 0.5 IU/mL OR ACT: 180 - 210 sec',
    actRange: [180, 210],
    antiXaRange: [0.3, 0.5],
    apttRange: [60, 85],
    reversalAgent: 'Protamine Sulfate (1 mg per 100 units heparin)',
  },
  BIVALIRUDIN: {
    id: 'BIVALIRUDIN',
    name: 'Bivalirudin (Direct Thrombin Inhibitor)',
    monitoringTarget: 'aPTT: 60 - 80 sec OR ECT: 2.0 - 2.5x control',
    actRange: [190, 230],
    antiXaRange: [0.0, 0.0],
    apttRange: [60, 80],
    reversalAgent: 'Hemofiltration / Fresh Frozen Plasma (Short half-life: 25 min)',
  },
  ARGATROBAN: {
    id: 'ARGATROBAN',
    name: 'Argatroban (HIT / Direct Thrombin Inhibitor)',
    monitoringTarget: 'aPTT: 1.5 - 3.0x baseline (55 - 75 sec)',
    actRange: [180, 220],
    antiXaRange: [0.0, 0.0],
    apttRange: [55, 75],
    reversalAgent: 'Discontinue infusion (Hepatic metabolism, half-life 45 min)',
  },
};

export const EMERGENCY_ECMO_PROTOCOLS = {
  CIRCUIT_THROMBOSIS: {
    id: 'CIRCUIT_THROMBOSIS',
    title: 'Code Oxygenator Thrombosis / Acute Circuit Clotting',
    severity: 'CRITICAL',
    triggerCriteria: 'Delta P > 60 mmHg OR sudden drop in post-membrane pO2 < 200 mmHg on 100% Sweep FiO2',
    actions: [
      'Notify ECMO Specialist, Perfusionist, and Attending Intensivist immediately.',
      'Prepare sterile backup ECMO console and pre-primed circuit.',
      'Increase mechanical ventilator support to 100% FiO2 and higher rates temporarily.',
      'Clamp lines simultaneously at 45-degree angle, switch console pump head, and de-air.',
      'Re-establish full flow, verify baseline pressures (P1, P2, P3), and inspect for fibrin strands.',
      'Check ACT, Anti-Xa, Fibrinogen, and Free Plasma Hemoglobin levels.',
    ],
  },
  AIR_EMBOLISM: {
    id: 'AIR_EMBOLISM',
    title: 'Code Air Embolism in Circuit',
    severity: 'CRITICAL',
    triggerCriteria: 'Ultrasonic air sensor trigger (>50uL air bubble) OR visible bubbles in arterial line',
    actions: [
      'Emergency clamp arterial reinfusion line instantly to prevent cerebral/systemic embolization.',
      'Stop blood pump and place patient in Trendelenburg position.',
      'Vent air through oxygenator purge line and access bridge using sterile 50mL syringes.',
      'Flush circuit until ultrasonic bubble detectors confirm zero microbubbles.',
      'Unclamp line and resume gradual flow ramping under continuous visual inspection.',
    ],
  },
  ACCIDENTAL_DECANNULATION: {
    id: 'ACCIDENTAL_DECANNULATION',
    title: 'Code Accidental Decannulation / Cannula Displacement',
    severity: 'CRITICAL',
    triggerCriteria: 'Sudden loss of circuit flow < 0.5 LPM + P1 collapse < -200 mmHg or massive external hemorrhage',
    actions: [
      'Apply direct firm manual compression on vascular insertion site immediately.',
      'Emergency clamp both drainage and reinfusion lines to prevent air entrainment.',
      'Switch mechanical ventilator to rescue mode: FiO2 1.0, PEEP 16, RR 24.',
      'Initiate massive transfusion protocol (MTP) if severe blood loss occurs.',
      'Call emergency surgical cutdown/vascular access team for emergency re-cannulation.',
    ],
  },
  HARLEQUIN_SYNDROME: {
    id: 'HARLEQUIN_SYNDROME',
    title: 'North-South / Harlequin Differential Hypoxemia Protocol (VA ECMO)',
    severity: 'HIGH_RISK',
    triggerCriteria: 'Right radial arterial SpO2 < 88% with femoral arterial SpO2 > 98%',
    actions: [
      'Confirm differential hypoxemia between upper body (native cardiac output with poorly oxygenated lung blood) and lower body (retrograde ECMO oxygenated blood).',
      'Increase ventilator FiO2 and optimize PEEP to improve native lung gas exchange.',
      'Increase ECMO flow rate to push mixing cloud higher into the aortic arch.',
      'If unresolved, convert to V-AV ECMO configuration by adding right internal jugular arterial/venous reinfusion limb.',
    ],
  },
};

export const INITIAL_ECMO_PATIENTS = [
  {
    id: 'PT-ECMO-8801',
    name: 'Elena Rostova, MD',
    mrn: 'MRN-7749201',
    age: 38,
    weightKg: 68,
    heightCm: 168,
    gender: 'Female',
    diagnosis: 'Severe Viral ARDS with Cytokine Storm & Barotrauma',
    ecmoMode: 'VV_ECMO',
    cannulaDrainage: '25 Fr Multi-Stage Femoral Venous (Right)',
    cannulaReinfusion: '19 Fr Bio-Flex Internal Jugular Venous (Right)',
    cannulationDate: '2026-08-18T04:30:00Z',
    daysOnECMO: 3.8,
    pumpRPM: 3850,
    bloodFlowLPM: 4.8,
    sweepGasFlowLPM: 5.5,
    sweepFiO2: 1.0,
    p1PrePump: -42,
    p2PreOxy: 185,
    p3PostOxy: 156,
    transmembraneDeltaP: 29,
    arterialPaO2: 88,
    arterialPaCO2: 41,
    postOxyPaO2: 445,
    postOxyPaCO2: 32,
    svO2Percent: 76.5,
    anticoagulant: 'UFH',
    infusionRate: '18.5 units/kg/hr',
    actSeconds: 198,
    antiXa: 0.38,
    platelets: 142000,
    fibrinogenMgDl: 285,
    plasmaFreeHbMgDl: 12,
    ventMode: 'PC-BIPAP (Resting Lung)',
    ventPplat: 22,
    ventPEEP: 12,
    ventDrivingPressure: 10,
    ventRR: 8,
    ventVtMl: 220,
    ventFiO2: 0.35,
    mechanicalPower: 7.8,
    murrayScore: 3.2,
    clinicalStatus: 'STABLE_ECMO_LUNG_REST',
  },
  {
    id: 'PT-ECMO-8802',
    name: 'Marcus Vance',
    mrn: 'MRN-9031842',
    age: 54,
    weightKg: 84,
    heightCm: 178,
    gender: 'Male',
    diagnosis: 'Post-Anterior STEMI Cardiogenic Shock & E-CPR Rescue',
    ecmoMode: 'VA_ECMO',
    cannulaDrainage: '23 Fr Femoral Venous (Left)',
    cannulaReinfusion: '17 Fr Femoral Arterial + 7 Fr Distal Perfusion (Right)',
    cannulationDate: '2026-08-20T11:15:00Z',
    daysOnECMO: 1.5,
    pumpRPM: 4200,
    bloodFlowLPM: 5.2,
    sweepGasFlowLPM: 4.2,
    sweepFiO2: 0.9,
    p1PrePump: -65,
    p2PreOxy: 240,
    p3PostOxy: 198,
    transmembraneDeltaP: 42,
    arterialPaO2: 120,
    arterialPaCO2: 39,
    postOxyPaO2: 480,
    postOxyPaCO2: 34,
    svO2Percent: 72.0,
    anticoagulant: 'BIVALIRUDIN',
    infusionRate: '0.12 mg/kg/hr',
    actSeconds: 215,
    antiXa: 0.0,
    platelets: 118000,
    fibrinogenMgDl: 210,
    plasmaFreeHbMgDl: 18,
    ventMode: 'VC-CMV (Protective)',
    ventPplat: 24,
    ventPEEP: 10,
    ventDrivingPressure: 14,
    ventRR: 12,
    ventVtMl: 380,
    ventFiO2: 0.40,
    mechanicalPower: 12.4,
    murrayScore: 2.5,
    clinicalStatus: 'CARDIOGENIC_RECOVERY_PHASE',
  },
  {
    id: 'PT-ECMO-8803',
    name: 'Sophia Chen-Kowalski',
    mrn: 'MRN-5510294',
    age: 29,
    weightKg: 58,
    heightCm: 162,
    gender: 'Female',
    diagnosis: 'Amniotic Fluid Embolism with Catastrophic ARDS & DIC',
    ecmoMode: 'VV_ECMO',
    cannulaDrainage: '27 Fr Dual-Lumen Bicaval Avalon (RIJ)',
    cannulaReinfusion: 'Dual-Lumen PA Reinfusion Port',
    cannulationDate: '2026-08-21T01:40:00Z',
    daysOnECMO: 0.9,
    pumpRPM: 4500,
    bloodFlowLPM: 5.6,
    sweepGasFlowLPM: 7.0,
    sweepFiO2: 1.0,
    p1PrePump: -88,
    p2PreOxy: 295,
    p3PostOxy: 232,
    transmembraneDeltaP: 63,
    arterialPaO2: 64,
    arterialPaCO2: 56,
    postOxyPaO2: 310,
    postOxyPaCO2: 44,
    svO2Percent: 63.8,
    anticoagulant: 'ARGATROBAN',
    infusionRate: '1.2 mcg/kg/min',
    actSeconds: 174,
    antiXa: 0.0,
    platelets: 68000,
    fibrinogenMgDl: 135,
    plasmaFreeHbMgDl: 34,
    ventMode: 'APRV / BiLevel Rescue',
    ventPplat: 28,
    ventPEEP: 14,
    ventDrivingPressure: 14,
    ventRR: 14,
    ventVtMl: 260,
    ventFiO2: 0.60,
    mechanicalPower: 16.2,
    murrayScore: 3.8,
    clinicalStatus: 'HIGH_DELTA_P_MEMBRANE_ALERT',
  },
];
