/**
 * Emergency and mass-casualty triage clinical rules.
 *
 * The constants in this module are intentionally separated from the calculation
 * service. They provide a reviewable policy surface for START/JumpSTART triage,
 * NEWS2 escalation, sepsis screening, hemorrhage recognition and emergency team
 * activation. The command station is decision support only: clinicians retain
 * responsibility for reassessment, local policy and definitive treatment.
 */

export const TRIAGE_CATEGORIES = Object.freeze({
  IMMEDIATE: {
    id: 'IMMEDIATE',
    label: 'Immediate / Red',
    color: 'rose',
    priority: 1,
    disposition: 'Resuscitation bay or immediate lifesaving intervention',
  },
  DELAYED: {
    id: 'DELAYED',
    label: 'Delayed / Yellow',
    color: 'amber',
    priority: 2,
    disposition: 'Monitored treatment area with serial reassessment',
  },
  MINOR: {
    id: 'MINOR',
    label: 'Minor / Green',
    color: 'emerald',
    priority: 3,
    disposition: 'Ambulatory treatment area',
  },
  EXPECTANT: {
    id: 'EXPECTANT',
    label: 'Expectant / Black',
    color: 'slate',
    priority: 4,
    disposition: 'Expectant care per incident command and local protocol',
  },
});

export const START_THRESHOLDS = Object.freeze({
  adult: {
    respiratoryRateHigh: 30,
    radialPulseAbsentMeansImmediate: true,
    capillaryRefillSecondsHigh: 2,
    followsCommandsRequired: true,
  },
  pediatric: {
    respiratoryRateLow: 15,
    respiratoryRateHigh: 45,
    pulseCheckAfterRescueBreaths: true,
    rescueBreaths: 5,
    avpuMentalStatusImmediate: ['P', 'U'],
  },
});

export const NEWS2_THRESHOLDS = Object.freeze({
  low: { min: 0, max: 4, response: 'Ward-level monitoring with documented reassessment plan' },
  lowSingleThree: {
    min: 3,
    max: 3,
    response: 'Urgent registered-clinician review for a single parameter scoring three',
  },
  medium: { min: 5, max: 6, response: 'Urgent review by acute-care competent clinician or team' },
  high: { min: 7, max: 20, response: 'Emergency assessment by critical-care response team' },
});

export const HEMORRHAGE_THRESHOLDS = Object.freeze({
  shockIndexWarning: 0.9,
  shockIndexCritical: 1.4,
  modifiedShockIndexWarning: 1.3,
  systolicPressureCriticalMmHg: 90,
  lactateCriticalMmolL: 4,
  baseDeficitCritical: -6,
  estimatedBloodLossCriticalMl: 1500,
  transfusedUnitsFourHours: 4,
});

export const PROTOCOL_DEFINITIONS = Object.freeze({
  CODE_RED: {
    id: 'CODE_RED',
    label: 'Code Red Resuscitation',
    authority: 'Emergency Department Resuscitation Policy',
    acknowledgementSeconds: 60,
    requiredRoles: [
      'Emergency physician',
      'Resuscitation nurse',
      'Respiratory therapist',
      'Clinical pharmacist',
    ],
    checklist: [
      'Confirm team leader, airway lead and closed-loop communications',
      'Apply continuous ECG, SpO2, non-invasive pressure and capnography monitoring',
      'Establish two large-bore IV lines or intraosseous access',
      'Obtain point-of-care blood gas, glucose, lactate and type-and-screen',
      'Perform structured primary survey with repeat vital signs',
    ],
  },
  CODE_STEMI: {
    id: 'CODE_STEMI',
    label: 'Code STEMI / Cath Lab Activation',
    authority: 'ACC/AHA acute coronary syndrome pathway',
    acknowledgementSeconds: 300,
    requiredRoles: [
      'Emergency physician',
      'Interventional cardiologist',
      'Cath laboratory charge nurse',
      'Cardiac critical-care bed manager',
    ],
    checklist: [
      'Acquire and clinician-interpret 12-lead ECG without delaying stabilization',
      'Record symptom onset and first-medical-contact timestamp',
      'Screen for antiplatelet and anticoagulant contraindications',
      'Transmit ECG and activate catheterization laboratory per local pathway',
      'Document reperfusion decision and exception reason when applicable',
    ],
  },
  MASSIVE_TRANSFUSION: {
    id: 'MASSIVE_TRANSFUSION',
    label: 'Massive Transfusion Protocol',
    authority: 'Institutional trauma and transfusion medicine policy',
    acknowledgementSeconds: 180,
    requiredRoles: [
      'Trauma or emergency team leader',
      'Transfusion medicine',
      'Blood bank runner',
      'Operating theatre coordinator',
    ],
    checklist: [
      'Notify blood bank with patient identifier and emergency-release authorization',
      'Apply active warming and use a fluid warmer for blood components',
      'Trend temperature, ionized calcium, fibrinogen, INR, platelets and blood gas',
      'Control hemorrhage through surgery, interventional radiology or direct measures',
      'Reassess continuation after every cooler and communicate protocol termination',
    ],
  },
  SEPSIS_HOUR_ONE: {
    id: 'SEPSIS_HOUR_ONE',
    label: 'Sepsis Hour-One Escalation',
    authority: 'Surviving Sepsis Campaign bundle adapted to local policy',
    acknowledgementSeconds: 300,
    requiredRoles: [
      'Emergency physician',
      'Sepsis response nurse',
      'Clinical pharmacist',
      'Critical-care outreach',
    ],
    checklist: [
      'Measure lactate and repeat when initially elevated',
      'Obtain blood cultures before antimicrobials when this causes no meaningful delay',
      'Administer antimicrobials according to source and local resistance guidance',
      'Give crystalloid for hypotension or hypoperfusion with repeated responsiveness checks',
      'Escalate vasopressor support to maintain the clinician-selected MAP target',
    ],
  },
});

export const TRIAGE_PATIENT_FIXTURES = Object.freeze([
  {
    id: 'ED-24017',
    mrn: 'MRN-904-771',
    name: 'Maya Chen',
    ageYears: 34,
    sex: 'Female',
    location: 'Resus 01',
    presentingProblem: 'Blunt polytrauma with suspected pelvic hemorrhage',
    arrivalMode: 'Prehospital trauma team',
    ambulatory: false,
    spontaneousBreathing: true,
    pulsePresent: true,
    followsCommands: true,
    mentalStatus: 'A',
    respiratoryRate: 32,
    heartRate: 132,
    systolicBp: 82,
    diastolicBp: 48,
    map: 59,
    spo2: 93,
    temperatureC: 35.4,
    capillaryRefillSeconds: 4,
    lactate: 5.8,
    baseDeficit: -8.1,
    gcs: 14,
    supplementalOxygen: true,
    estimatedBloodLossMl: 1800,
    unitsRbcLastFourHours: 2,
    triageCategory: 'IMMEDIATE',
    activeProtocol: 'MASSIVE_TRANSFUSION',
    allergies: ['Penicillin'],
  },
  {
    id: 'ED-24021',
    mrn: 'MRN-601-225',
    name: 'Arjun Mehta',
    ageYears: 61,
    sex: 'Male',
    location: 'Resus 02',
    presentingProblem: 'Crushing substernal pain with anterior ST elevation',
    arrivalMode: 'Ambulance',
    ambulatory: false,
    spontaneousBreathing: true,
    pulsePresent: true,
    followsCommands: true,
    mentalStatus: 'A',
    respiratoryRate: 24,
    heartRate: 112,
    systolicBp: 96,
    diastolicBp: 61,
    map: 73,
    spo2: 95,
    temperatureC: 36.7,
    capillaryRefillSeconds: 3,
    lactate: 2.7,
    baseDeficit: -2.2,
    gcs: 15,
    supplementalOxygen: false,
    estimatedBloodLossMl: 0,
    unitsRbcLastFourHours: 0,
    triageCategory: 'IMMEDIATE',
    activeProtocol: 'CODE_STEMI',
    allergies: [],
  },
  {
    id: 'ED-24029',
    mrn: 'MRN-188-403',
    name: 'Noah Williams',
    ageYears: 7,
    sex: 'Male',
    location: 'Pediatric 03',
    presentingProblem: 'Smoke inhalation with partial-thickness upper-limb burns',
    arrivalMode: 'Family transport',
    ambulatory: true,
    spontaneousBreathing: true,
    pulsePresent: true,
    followsCommands: true,
    mentalStatus: 'A',
    respiratoryRate: 28,
    heartRate: 118,
    systolicBp: 104,
    diastolicBp: 66,
    map: 79,
    spo2: 97,
    temperatureC: 37.1,
    capillaryRefillSeconds: 2,
    lactate: 1.9,
    baseDeficit: -1.1,
    gcs: 15,
    supplementalOxygen: true,
    estimatedBloodLossMl: 0,
    unitsRbcLastFourHours: 0,
    triageCategory: 'MINOR',
    activeProtocol: null,
    allergies: ['Latex'],
  },
  {
    id: 'ED-24034',
    mrn: 'MRN-755-099',
    name: 'Fatima Rahman',
    ageYears: 72,
    sex: 'Female',
    location: 'High Acuity 05',
    presentingProblem: 'Probable pneumonia with sepsis-associated hypotension',
    arrivalMode: 'Ambulance',
    ambulatory: false,
    spontaneousBreathing: true,
    pulsePresent: true,
    followsCommands: false,
    mentalStatus: 'V',
    respiratoryRate: 27,
    heartRate: 121,
    systolicBp: 88,
    diastolicBp: 50,
    map: 63,
    spo2: 90,
    temperatureC: 39.1,
    capillaryRefillSeconds: 4,
    lactate: 4.4,
    baseDeficit: -5.4,
    gcs: 13,
    supplementalOxygen: true,
    estimatedBloodLossMl: 0,
    unitsRbcLastFourHours: 0,
    triageCategory: 'IMMEDIATE',
    activeProtocol: 'SEPSIS_HOUR_ONE',
    allergies: ['Sulfonamides'],
  },
]);

export default {
  TRIAGE_CATEGORIES,
  START_THRESHOLDS,
  NEWS2_THRESHOLDS,
  HEMORRHAGE_THRESHOLDS,
  PROTOCOL_DEFINITIONS,
  TRIAGE_PATIENT_FIXTURES,
};
