/**
 * Neurocritical Care & Multimodal Neuromonitoring (MMN) Data Models
 * Adheres to Brain Trauma Foundation (BTF 4th Edition) Guidelines,
 * Seattle International Severe Traumatic Brain Injury Consensus Conference (SIBICC) Tiered Protocols,
 * Neurocritical Care Society (NCS) Multimodal Neuromonitoring Guidelines,
 * Automated Quantitative Pupillometry (NPi) Standards, and FDA 21 CFR Part 11 Audit Integrity.
 */

export const NEURO_MONITORING_MODALITIES = {
  ICP_CPP: {
    id: "ICP_CPP",
    name: "Intracranial & Cerebral Perfusion Pressure",
    deviceTypes: ["Codman Microsensor ICP", "Camino Fiberoptic Parenchymal Transducer", "External Ventricular Drain (EVD) strain gauge"],
    targetICP: [0, 20], // mmHg (BTF threshold <= 22 mmHg)
    targetCPP: [60, 70], // mmHg
    criticalICP: 22,
    criticalLowCPP: 50,
    criticalHighCPP: 90,
  },
  PBTO2_OXYGENATION: {
    id: "PBTO2_OXYGENATION",
    name: "Brain Tissue Oxygen Partial Pressure (PbtO2)",
    deviceTypes: ["Licox Brain Tissue Oxygen Catheter", "Raumedic Neurovent-P-O2"],
    normalMin: 25, // mmHg
    cautionHypoxia: 20, // mmHg
    severeIschemia: 15, // mmHg (Triggers immediate SIBICC hypoxia protocol)
    targetPbtO2: [25, 45],
  },
  PUPILLOMETRY_NPI: {
    id: "PUPILLOMETRY_NPI",
    name: "Automated Quantitative Infrared Pupillometry",
    scale: "Neurological Pupil index (NPi: 0.0 - 5.0)",
    normalRange: [3.0, 5.0],
    abnormalSluggish: [1.0, 2.9],
    nonReactiveAtonic: 0.0,
    pupilSizeNormalMm: [2.0, 4.5],
    constrictionVelocityNormalMmS: [0.8, 2.5],
  },
  TCD_VASOSPASM: {
    id: "TCD_VASOSPASM",
    name: "Transcranial Doppler (TCD) Sonography",
    vessel: "Middle Cerebral Artery (MCA) & Extracranial Internal Carotid (ICA)",
    normalVmcaLpm: [45, 80], // cm/s
    mildVasospasmVmca: [120, 159], // cm/s
    moderateVasospasmVmca: [160, 199], // cm/s
    severeVasospasmVmca: 200, // cm/s
    lindegaardRatioThresholds: {
      normal: 3.0,
      hyperemia: 3.0, // High VMCA with LR < 3 = hyperemia, not vasospasm
      moderateVasospasm: 4.5,
      severeVasospasm: 6.0,
    },
    pulsatilityIndexTarget: [0.8, 1.2],
  },
  CEREBRAL_MICRODIALYSIS: {
    id: "CEREBRAL_MICRODIALYSIS",
    name: "Cerebral Microdialysis Biomarkers",
    lactatePyruvateRatioNormal: [15, 25],
    lprIschemicThreshold: 25,
    lprMitochondrialCrisis: 40,
    brainGlucoseNormalMmol: [1.0, 3.0],
    brainGlucoseNeuroglycopenia: 0.8, // mmol/L
    glycerolCellDamageThreshold: 100, // umol/L
  },
  CEEG_ELECTROPHYSIOLOGY: {
    id: "CEEG_ELECTROPHYSIOLOGY",
    name: "Continuous EEG & Quantitative Spectral Analysis",
    targetBurstSuppressionRatio: [60, 85], // % for pharmacological coma
    criticalIctalBurdenPercent: 20, // % of hour spent in ictal/periodic discharges
    alphaDeltaRatioNormal: [1.2, 3.0],
    adrIschemicDropThreshold: 0.8,
  },
};

export const SIBICC_TIER_PROTOCOLS = {
  TIER_0: {
    tier: "Tier 0: Foundational Neuro-Protective Care",
    indication: "Standard baseline protocol for all Severe TBI & Acute Brain Injury ICU admissions",
    interventions: [
      "Head of Bed elevation 30 degrees with neutral neck alignment to maximize jugular venous return",
      "Target normothermia (36.0 - 37.5°C) with active surface or intravascular temperature management (TTM)",
      "Baseline analgesia and light-to-moderate sedation (target RASS -1 to -2)",
      "Target normovolemia with isotonic crystalloids (Serum Sodium 140 - 145 mEq/L, CVP 6 - 10 mmHg)",
      "Target normoxia (PaO2 80 - 120 mmHg, SpO2 >= 95%) and normocapnia (PaCO2 35 - 40 mmHg)",
      "Maintain MAP >= 80 mmHg to preserve baseline cerebral perfusion",
    ],
  },
  TIER_1: {
    tier: "Tier 1: Early ICP & Hypoxia Escalation",
    indication: "Sustained ICP > 22 mmHg for > 5 min OR PbtO2 < 20 mmHg despite Tier 0",
    interventions: [
      "EVD CSF Drainage: Open external ventricular drain for intermittent (2-5 min) or continuous CSF drainage at 10-15 cmH2O",
      "Hyperosmolar Bolus Therapy: 20% Mannitol (0.5 - 1.0 g/kg IV) OR 3% Hypertonic Saline (250 mL IV over 15 min)",
      "Target Serum Osmolality 300 - 320 mOsm/kg, Serum Sodium 145 - 150 mEq/L",
      "Neuromuscular blockade test bolus (Cisatracurium 0.15 mg/kg) if shivering or ventilator dyssynchrony present",
      "Optimize CPP target to 60 - 70 mmHg using Norepinephrine infusion titrated to invasive arterial line",
    ],
  },
  TIER_2: {
    tier: "Tier 2: Refractory Intracranial Hypertension Escalation",
    indication: "Failure of Tier 1 with persistent ICP > 22 mmHg OR PbtO2 < 15 mmHg",
    interventions: [
      "Continuous Neuromuscular Blockade: Continuous Cisatracurium infusion monitored with Train-of-Four (target 1-2 twitches)",
      "Mild Hyperventilation: Titrate PaCO2 down to 30 - 35 mmHg under continuous PbtO2 / SjvO2 monitoring to prevent ischemia",
      "Hyperosmolar Infusion Target: Serum Sodium 150 - 155 mEq/L with 23.4% NaCl rescue bolus (30 mL over 10 min)",
      "PRx-Guided CPP Optimization: Individualized autoregulatory CPP targeting using automated PRx curve minima",
      "Neuromonitoring Review: Perform emergent repeat non-contrast head CT to rule out delayed hematoma or hydrocephalus",
    ],
  },
  TIER_3: {
    tier: "Tier 3: Salvage Refractory Interventions",
    indication: "Life-threatening intractable intracranial hypertension failing Tier 1 and Tier 2",
    interventions: [
      "Barbiturate Coma Therapy: High-dose Pentobarbital (5-10 mg/kg loading, then 1-3 mg/kg/hr) targeting continuous EEG burst suppression (10-15 bursts/min)",
      "Emergent Surgical Decompressive Craniectomy: Primary/Secondary unilateral fronto-temporo-parietal or bifrontal craniectomy",
      "Moderate Therapeutic Hypothermia: Cool core body temperature to 32.0 - 34.0°C with automated endovascular feedback cooling",
      "Profound Hyperventilation Rescue: Emergency PaCO2 < 30 mmHg strictly as bridging maneuver to operating room",
    ],
  },
};

export const LUNDBERG_WAVE_CLASSIFICATION = {
  A_WAVES: {
    name: "Lundberg A Waves (Plateau Waves)",
    amplitude: "50 - 100 mmHg sustained for 5 - 20 minutes",
    clinicalSignificance: "Critical reduction in intracranial compliance with near-total exhaustion of compensatory reserve. High risk of immediate uncal or transtentorial herniation.",
    urgency: "EMERGENCY_HERNIATION_RISK",
    immediateAction: "Initiate emergency hyperosmolar bolus, hyperventilation, and alert neurosurgery.",
  },
  B_WAVES: {
    name: "Lundberg B Waves (Rhythmic Oscillations)",
    amplitude: "10 - 20 mmHg oscillating at 0.5 - 2 waves/minute",
    clinicalSignificance: "Unstable cerebral vasospasm or intracranial compliance impairment reflecting oscillatory cerebral blood flow.",
    urgency: "HIGH_ALERT_UNSTABLE",
    immediateAction: "Deepen sedation, verify EVD patency, and check autoregulation index (PRx).",
  },
  C_WAVES: {
    name: "Lundberg C Waves (Vasomotor Traube-Hering Waves)",
    amplitude: "4 - 8 mmHg oscillating at 4 - 8 waves/minute",
    clinicalSignificance: "Normal physiological vasomotor oscillations coupled to systemic arterial pressure fluctuations.",
    urgency: "PHYSIOLOGIC_STABLE",
    immediateAction: "Continue standard neuro-intensive surveillance.",
  },
};

export const EMERGENCY_NEURO_PROTOCOLS = {
  CODE_BRAIN_HERNIATION: {
    id: "CODE_BRAIN_HERNIATION",
    title: "Code Acute Transtentorial / Uncal Brain Herniation",
    severity: "LIFE_THREATENING",
    triggerCriteria: "Sudden unilateral/bilateral pupillary dilation (NPi = 0) + ICP > 30 mmHg OR Cushing Triad (Hypertension, Bradycardia, Respiratory Depression)",
    actions: [
      "Announce Code Brain Herniation and page On-Call Neurosurgeon & Neurointensivist STAT.",
      "Administer 23.4% Hypertonic Saline (30 mL IV push over 10 min via central line) OR 20% Mannitol (1.5 g/kg rapid IV push).",
      "Increase ventilator rate to acutely hyperventilate to PaCO2 28 - 32 mmHg as bridging rescue.",
      "Level EVD to 0 cmH2O and open wide to facilitate rapid CSF decompression.",
      "Elevate Head of Bed to 45 degrees, ensure zero jugular compression / release tight cervical collar.",
      "Prepare patient for emergent transport to Operating Suite for Decompressive Craniectomy or hematoma evacuation.",
    ],
  },
  CODE_STATUS_EPILEPTICUS: {
    id: "CODE_STATUS_EPILEPTICUS",
    title: "Code Refractory Status Epilepticus (RSE)",
    severity: "CRITICAL_METABOLIC_CRISIS",
    triggerCriteria: "Continuous electrographic seizure activity > 5 min OR recurrent seizures without recovery of consciousness",
    actions: [
      "Administer IV Lorazepam 0.1 mg/kg (up to 4 mg) or Midazolam 10 mg IM/IV.",
      "Load second-line IV anticonvulsant: Levetiracetam 60 mg/kg (max 4500 mg) OR Fosphenytoin 20 mg PE/kg over 10 min.",
      "If seizures persist > 20 min: Initiate Continuous IV anesthetic infusion with Propofol (2-5 mg/kg/hr) or Midazolam (0.2-2.0 mg/kg/hr).",
      "Connect Continuous 21-channel ICU EEG; titrate anesthetic infusion to achieve 60-80% Burst Suppression Ratio (BSR).",
      "Maintain mean arterial pressure with Norepinephrine to counteract anesthetic-induced vasodilatory hypotension.",
    ],
  },
  CODE_VASOSPASM_DCI: {
    id: "CODE_VASOSPASM_DCI",
    title: "Code Delayed Cerebral Ischemia (DCI) / SAH Severe Vasospasm",
    severity: "HIGH_RISK_ISCHEMIA",
    triggerCriteria: "TCD MCA Vmean > 200 cm/s with Lindegaard Ratio > 6.0 OR new focal neurological deficit in aneurysmal SAH",
    actions: [
      "Initiate Induced Hypertension Protocol: Norepinephrine infusion titrated to systolic BP 160 - 180 mmHg (or MAP > 95 mmHg).",
      "Maintain strict euvolemia (avoid hypervolemia/CVP > 12 mmHg due to pulmonary edema risk); target CVP 6-8 mmHg.",
      "Verify oral Nimodipine 60 mg q4h dosing adherence.",
      "Perform urgent CTA/CTP (CT Perfusion) to identify salvageable ischemic penumbra and vessel narrowing.",
      "Contact Interventional Neuroradiology for urgent endovascular intra-arterial vasodilator infusion (Milrinone/Verapamil) or transluminal balloon angioplasty.",
    ],
  },
};

export const INITIAL_NEURO_PATIENTS = [
  {
    id: "PT-NEURO-9401",
    name: "Commander Gabriel Sterling",
    mrn: "MRN-8823901",
    age: 42,
    gender: "Male",
    weightKg: 82,
    heightCm: 183,
    diagnosis: "Severe Traumatic Brain Injury (sTBI) with Right Epidural & Contusional Hemorrhage",
    admissionDate: "2026-08-20T14:15:00Z",
    daysInNeuroICU: 2.3,
    marshallCTGrade: "Type III (High Risk Swelling)",
    gcsEye: 1,
    gcsVerbal: 1,
    gcsMotor: 3,
    gcsTotal: 5,
    fourScoreEye: 1,
    fourScoreMotor: 2,
    fourScoreBrainstem: 3,
    fourScoreRespiration: 1,
    fourScoreTotal: 7,
    icpMmHg: 23.4,
    mapMmHg: 88.0,
    cppMmHg: 64.6,
    optimalCppMmHg: 68.0,
    prxAutoregulationIndex: 0.38,
    pbtO2MmHg: 18.2,
    brainTempC: 37.8,
    coreTempC: 37.4,
    pupilLeftSizeMm: 3.2,
    pupilRightSizeMm: 4.8,
    npiLeft: 3.6,
    npiRight: 1.8,
    evdStatus: "OPEN_DRAINING",
    evdHeightCmH2O: 10,
    evdOutputPerHourMl: 14.5,
    tcdVmcaLeft: 92,
    tcdVmcaRight: 148,
    tcdLindegaardRatio: 4.2,
    tcdPulsatilityIndex: 1.45,
    microdialysisLPR: 34.2,
    microdialysisGlucoseMmol: 0.92,
    microdialysisGlycerolUmol: 142,
    ceegBurstSuppressionPercent: 0,
    ceegAlphaDeltaRatio: 0.95,
    ceegSeizureBurdenPercent: 4.0,
    lundbergWaveType: "B_WAVES",
    sedationAgent: "Propofol + Fentanyl",
    sedationDose: "50 mcg/kg/min + 100 mcg/hr",
    hyperosmolarAgent: "3% Hypertonic Saline @ 50 mL/hr",
    serumSodiumMeqL: 149,
    serumOsmolalityMOsmKg: 312,
    currentSIBICCTier: "TIER_1",
    clinicalStatus: "HIGH_ALERT_INTRACRANIAL_HYPERTENSION",
  },
  {
    id: "PT-NEURO-9402",
    name: "Dr. Vivienne Chen, PhD",
    mrn: "MRN-7734190",
    age: 51,
    gender: "Female",
    weightKg: 64,
    heightCm: 165,
    diagnosis: "Aneurysmal Subarachnoid Hemorrhage (aSAH Hunt-Hess 4, Fisher 3) s/p ACoA Coiling",
    admissionDate: "2026-08-17T09:30:00Z",
    daysInNeuroICU: 5.5,
    marshallCTGrade: "Diffuse Injury II",
    gcsEye: 2,
    gcsVerbal: 2,
    gcsMotor: 4,
    gcsTotal: 8,
    fourScoreEye: 2,
    fourScoreMotor: 3,
    fourScoreBrainstem: 4,
    fourScoreRespiration: 2,
    fourScoreTotal: 11,
    icpMmHg: 16.8,
    mapMmHg: 104.0,
    cppMmHg: 87.2,
    optimalCppMmHg: 75.0,
    prxAutoregulationIndex: 0.12,
    pbtO2MmHg: 28.5,
    brainTempC: 37.0,
    coreTempC: 36.9,
    pupilLeftSizeMm: 2.8,
    pupilRightSizeMm: 2.7,
    npiLeft: 4.4,
    npiRight: 4.2,
    evdStatus: "CLAMPED_MONITORING",
    evdHeightCmH2O: 15,
    evdOutputPerHourMl: 6.0,
    tcdVmcaLeft: 188,
    tcdVmcaRight: 215,
    tcdLindegaardRatio: 6.4,
    tcdPulsatilityIndex: 1.18,
    microdialysisLPR: 22.4,
    microdialysisGlucoseMmol: 1.85,
    microdialysisGlycerolUmol: 68,
    ceegBurstSuppressionPercent: 0,
    ceegAlphaDeltaRatio: 1.62,
    ceegSeizureBurdenPercent: 0.0,
    lundbergWaveType: "C_WAVES",
    sedationAgent: "Dexmedetomidine",
    sedationDose: "0.8 mcg/kg/hr",
    hyperosmolarAgent: "Isotonic Saline Maintenance",
    serumSodiumMeqL: 142,
    serumOsmolalityMOsmKg: 295,
    currentSIBICCTier: "TIER_0",
    clinicalStatus: "SEVERE_VASOSPASM_INDUCED_HTN_ACTIVE",
  },
  {
    id: "PT-NEURO-9403",
    name: "Julian Vance, JD",
    mrn: "MRN-6619082",
    age: 63,
    gender: "Male",
    weightKg: 89,
    heightCm: 176,
    diagnosis: "Large Left Middle Cerebral Artery (MCA) Malignant Infarction s/p Decompressive Hemicraniectomy",
    admissionDate: "2026-08-19T20:00:00Z",
    daysInNeuroICU: 3.1,
    marshallCTGrade: "Surgically Evacuated Mass Lesion",
    gcsEye: 1,
    gcsVerbal: 1,
    gcsMotor: 2,
    gcsTotal: 4,
    fourScoreEye: 1,
    fourScoreMotor: 1,
    fourScoreBrainstem: 2,
    fourScoreRespiration: 0,
    fourScoreTotal: 4,
    icpMmHg: 28.6,
    mapMmHg: 92.0,
    cppMmHg: 63.4,
    optimalCppMmHg: 72.0,
    prxAutoregulationIndex: 0.54,
    pbtO2MmHg: 13.8,
    brainTempC: 38.2,
    coreTempC: 37.9,
    pupilLeftSizeMm: 5.4,
    pupilRightSizeMm: 3.0,
    npiLeft: 0.0,
    npiRight: 2.2,
    evdStatus: "OPEN_DRAINING",
    evdHeightCmH2O: 5,
    evdOutputPerHourMl: 22.0,
    tcdVmcaLeft: 42,
    tcdVmcaRight: 88,
    tcdLindegaardRatio: 2.1,
    tcdPulsatilityIndex: 1.95,
    microdialysisLPR: 48.5,
    microdialysisGlucoseMmol: 0.45,
    microdialysisGlycerolUmol: 280,
    ceegBurstSuppressionPercent: 72,
    ceegAlphaDeltaRatio: 0.42,
    ceegSeizureBurdenPercent: 18.5,
    lundbergWaveType: "A_WAVES",
    sedationAgent: "Pentobarbital Infusion + Midazolam",
    sedationDose: "3.5 mg/kg/hr + 0.3 mg/kg/hr",
    hyperosmolarAgent: "23.4% Hypertonic Saline Boluses PRN",
    serumSodiumMeqL: 156,
    serumOsmolalityMOsmKg: 328,
    currentSIBICCTier: "TIER_3",
    clinicalStatus: "CRITICAL_REFRACTORY_ICP_BARBITURATE_COMA",
  },
];
