/**
 * Sepsis Resuscitation & Antimicrobial Stewardship Clinical Decision Support Models.
 *
 * Implements Surviving Sepsis Campaign (SSC) International Guidelines 2021/2026,
 * Sepsis-3 consensus definitions, SOFA & qSOFA organ dysfunction criteria,
 * IDSA/ESCMID antimicrobial stewardship guidelines, and PK/PD therapeutic
 * drug monitoring targets (AUC24:MIC, %fT>MIC, Cmax:MIC).
 */

export const SEPSIS_SEVERITY_LEVELS = Object.freeze({
  SIRS: {
    id: 'SIRS',
    label: 'Systemic Inflammatory Response (SIRS)',
    color: 'amber',
    priority: 3,
    description: 'Systemic response to infectious or non-infectious insult without documented organ failure.',
  },
  SEPSIS: {
    id: 'SEPSIS',
    label: 'Sepsis (Organ Dysfunction)',
    color: 'orange',
    priority: 2,
    description: 'Life-threatening organ dysfunction caused by a dysregulated host response to infection (SOFA increase >= 2).',
  },
  SEPTIC_SHOCK: {
    id: 'SEPTIC_SHOCK',
    label: 'Septic Shock',
    color: 'rose',
    priority: 1,
    description: 'Sepsis with persistent hypotension requiring vasopressors to maintain MAP >= 65 mmHg and serum lactate > 2 mmol/L despite volume resuscitation.',
  },
  REFRACTORY_SHOCK: {
    id: 'REFRACTORY_SHOCK',
    label: 'Refractory Septic Shock',
    color: 'purple',
    priority: 1,
    description: 'Vasodilatory shock requiring escalating multi-agent vasopressors (Norepinephrine > 0.25 mcg/kg/min + Vasopressin) with metabolic acidosis.',
  },
});

export const SSC_BUNDLE_ITEMS = Object.freeze({
  LACTATE_INITIAL: {
    id: 'LACTATE_INITIAL',
    title: 'Measure Blood Lactate Level',
    targetMinutes: 60,
    rationale: 'Identifies tissue hypoperfusion; repeat within 2-4 hours if initial lactate > 2.0 mmol/L.',
    guidelineRef: 'SSC 2021 Recommendation 1.1',
  },
  BLOOD_CULTURES: {
    id: 'BLOOD_CULTURES',
    title: 'Obtain Blood Cultures Prior to Antibiotics',
    targetMinutes: 60,
    rationale: 'Two sets of aerobic and anaerobic blood cultures prior to antimicrobial therapy if no substantial delay (< 45 min).',
    guidelineRef: 'SSC 2021 Recommendation 1.2',
  },
  BROAD_ANTIBIOTICS: {
    id: 'BROAD_ANTIBIOTICS',
    title: 'Administer Broad-Spectrum IV Antimicrobials',
    targetMinutes: 60,
    rationale: 'Empirical broad-spectrum antimicrobial therapy covering all likely pathogens within 1 hour of recognition.',
    guidelineRef: 'SSC 2021 Recommendation 1.3',
  },
  FLUID_RESUSCITATION: {
    id: 'FLUID_RESUSCITATION',
    title: 'Rapid IV Crystalloid Bolus (30 mL/kg)',
    targetMinutes: 180,
    rationale: 'Balanced crystalloids for hypotension (MAP < 65 mmHg) or initial lactate >= 4.0 mmol/L within 3 hours.',
    guidelineRef: 'SSC 2021 Recommendation 1.4',
  },
  VASOPRESSORS: {
    id: 'VASOPRESSORS',
    title: 'Initiate Vasopressors for MAP >= 65 mmHg',
    targetMinutes: 60,
    rationale: 'Norepinephrine as first-choice vasopressor to restore and maintain MAP >= 65 mmHg during/after fluid loading.',
    guidelineRef: 'SSC 2021 Recommendation 1.5',
  },
  LACTATE_REPEAT: {
    id: 'LACTATE_REPEAT',
    title: 'Serial Lactate Reassessment & Clearance',
    targetMinutes: 240,
    rationale: 'Guide resuscitation targeting lactate clearance (> 10-20% decrease every 2 hours) towards normalization.',
    guidelineRef: 'SSC 2021 Recommendation 1.6',
  },
});

export const SOFA_SCORING_MATRIX = Object.freeze({
  respiration: [
    { score: 0, criteria: 'PaO2/FiO2 >= 400 mmHg (53.3 kPa)' },
    { score: 1, criteria: 'PaO2/FiO2 < 400 mmHg (53.3 kPa)' },
    { score: 2, criteria: 'PaO2/FiO2 < 300 mmHg (40 kPa)' },
    { score: 3, criteria: 'PaO2/FiO2 < 200 mmHg (26.7 kPa) with ventilatory support' },
    { score: 4, criteria: 'PaO2/FiO2 < 100 mmHg (13.3 kPa) with ventilatory support' },
  ],
  coagulation: [
    { score: 0, criteria: 'Platelets >= 150 x10^3/uL' },
    { score: 1, criteria: 'Platelets < 150 x10^3/uL' },
    { score: 2, criteria: 'Platelets < 100 x10^3/uL' },
    { score: 3, criteria: 'Platelets < 50 x10^3/uL' },
    { score: 4, criteria: 'Platelets < 20 x10^3/uL' },
  ],
  liver: [
    { score: 0, criteria: 'Bilirubin < 1.2 mg/dL (< 20 umol/L)' },
    { score: 1, criteria: 'Bilirubin 1.2-1.9 mg/dL (20-32 umol/L)' },
    { score: 2, criteria: 'Bilirubin 2.0-5.9 mg/dL (33-101 umol/L)' },
    { score: 3, criteria: 'Bilirubin 6.0-11.9 mg/dL (102-204 umol/L)' },
    { score: 4, criteria: 'Bilirubin >= 12.0 mg/dL (>= 204 umol/L)' },
  ],
  cardiovascular: [
    { score: 0, criteria: 'MAP >= 70 mmHg' },
    { score: 1, criteria: 'MAP < 70 mmHg' },
    { score: 2, criteria: 'Dopamine <= 5 or Dobutamine (any dose)' },
    { score: 3, criteria: 'Dopamine > 5 or Epinephrine <= 0.1 or Norepinephrine <= 0.1 mcg/kg/min' },
    { score: 4, criteria: 'Dopamine > 15 or Epinephrine > 0.1 or Norepinephrine > 0.1 mcg/kg/min' },
  ],
  cns: [
    { score: 0, criteria: 'Glasgow Coma Scale 15' },
    { score: 1, criteria: 'Glasgow Coma Scale 13-14' },
    { score: 2, criteria: 'Glasgow Coma Scale 10-12' },
    { score: 3, criteria: 'Glasgow Coma Scale 6-9' },
    { score: 4, criteria: 'Glasgow Coma Scale < 6' },
  ],
  renal: [
    { score: 0, criteria: 'Creatinine < 1.2 mg/dL' },
    { score: 1, criteria: 'Creatinine 1.2-1.9 mg/dL' },
    { score: 2, criteria: 'Creatinine 2.0-3.4 mg/dL' },
    { score: 3, criteria: 'Creatinine 3.5-4.9 mg/dL or Urine Output < 500 mL/day' },
    { score: 4, criteria: 'Creatinine >= 5.0 mg/dL or Urine Output < 200 mL/day' },
  ],
});

export const ANTIMICROBIAL_PK_PD_TARGETS = Object.freeze({
  VANCOMYCIN: {
    name: 'Vancomycin',
    class: 'Glycopeptide',
    pdIndex: 'AUC24/MIC',
    targetValue: '400 - 600 mg*h/L',
    targetMin: 400,
    targetMax: 600,
    troughTarget: '15 - 20 mcg/mL',
    monitoringFreq: 'Daily trough & Bayesian AUC estimation',
    toxicityAlert: 'Nephrotoxicity risk when AUC24 > 650 mg*h/L or trough > 20 mcg/mL',
    indications: ['MRSA Bacteremia', 'Septic Shock unknown focus', 'Severe soft tissue infection'],
  },
  MEROPENEM: {
    name: 'Meropenem',
    class: 'Carbapenem',
    pdIndex: '%fT > MIC',
    targetValue: '100% fT > 4x MIC',
    targetMin: 100,
    targetMax: 100,
    troughTarget: '8 - 16 mcg/mL',
    monitoringFreq: 'Steady-state mid-interval / trough in CRRT/ECMO',
    toxicityAlert: 'Neurotoxicity / seizure threshold at trough > 45 mcg/mL in renal failure',
    indications: ['ESBL Enterobacterales', 'Pseudomonas Septic Shock', 'Intra-abdominal Sepsis'],
  },
  PIPERACILLIN_TAZOBACTAM: {
    name: 'Piperacillin-Tazobactam',
    class: 'Beta-lactam / Beta-lactamase inhibitor',
    pdIndex: '%fT > MIC',
    targetValue: '100% fT > MIC (or >= 50% fT > 4x MIC)',
    targetMin: 100,
    targetMax: 100,
    troughTarget: '16 - 32 mcg/mL',
    monitoringFreq: 'Extended infusion (4h) or continuous infusion therapeutic monitoring',
    toxicityAlert: 'Synergistic acute kidney injury risk when co-administered with Vancomycin',
    indications: ['Hospital-Acquired Pneumonia', 'Urosepsis', 'Complicated skin infection'],
  },
  CEFEPIME: {
    name: 'Cefepime',
    class: '4th Gen Cephalosporin',
    pdIndex: '%fT > MIC',
    targetValue: '70-100% fT > MIC',
    targetMin: 70,
    targetMax: 100,
    troughTarget: '10 - 20 mcg/mL',
    monitoringFreq: 'Trough in renally impaired critically ill patients',
    toxicityAlert: 'Cefepime-induced neurotoxicity (CIN) / non-convulsive status epilepticus if trough > 22-35 mcg/mL',
    indications: ['Neutropenic Fever', 'Pseudomonal Sepsis', 'Severe UTI'],
  },
  COLISTIN: {
    name: 'Colistimethate Sodium (Colistin)',
    class: 'Polymyxin',
    pdIndex: 'AUC24/MIC',
    targetValue: '>= 50 mg*h/L (average steady-state 2 mg/L)',
    targetMin: 50,
    targetMax: 70,
    troughTarget: '2 - 3.5 mcg/mL',
    monitoringFreq: 'Serum colistin concentration at 48 hours',
    toxicityAlert: 'High acute tubular necrosis nephrotoxicity and neuromuscular blockade',
    indications: ['MDR/XDR Acinetobacter baumannii', 'Carbapenem-Resistant Enterobacteriaceae (CRE)'],
  },
});

export const PATHOGEN_ANTIBIOGRAM_CATALOG = Object.freeze([
  {
    pathogen: 'Staphylococcus aureus (MRSA)',
    gram: 'Gram-positive cocci in clusters',
    prevalence: 'High ICU risk',
    susceptibleTo: ['Vancomycin', 'Daptomycin', 'Linezolid', 'Ceftaroline'],
    resistantTo: ['Oxacillin', 'Cefazolin', 'Ampicillin-Sulbactam'],
    micBreakpoints: { Vancomycin: 1.0, Daptomycin: 0.5, Linezolid: 2.0 },
    deEscalationOpportunity: 'Switch to Cefazolin/Oxacillin if blood culture yields MSSA; stop if cultures negative at 48h.',
  },
  {
    pathogen: 'Pseudomonas aeruginosa',
    gram: 'Gram-negative bacillus',
    prevalence: 'Ventilator-associated pneumonia & catheter sepsis',
    susceptibleTo: ['Meropenem', 'Cefepime', 'Piperacillin-Tazobactam', 'Tobramycin', 'Colistin'],
    resistantTo: ['Ceftriaxone', 'Ertapenem', 'Ampicillin'],
    micBreakpoints: { Meropenem: 2.0, Cefepime: 4.0, PiperacillinTazo: 16.0 },
    deEscalationOpportunity: 'Monotherapy de-escalation once susceptibility confirmed; avoid redundant double GNR coverage.',
  },
  {
    pathogen: 'Klebsiella pneumoniae (ESBL)',
    gram: 'Gram-negative bacillus',
    prevalence: 'Intra-abdominal & urosepsis',
    susceptibleTo: ['Meropenem', 'Ertapenem', 'Amikacin', 'Ceftazidime-Avibactam'],
    resistantTo: ['Ceftriaxone', 'Cefotaxime', 'Aztreonam', 'Ciprofloxacin'],
    micBreakpoints: { Meropenem: 0.5, Ertapenem: 0.25, CeftazidimeAvibactam: 1.0 },
    deEscalationOpportunity: 'De-escalate from Meropenem to Ertapenem for once-daily step-down if not in septic shock.',
  },
  {
    pathogen: 'Streptococcus pneumoniae',
    gram: 'Gram-positive diplococci',
    prevalence: 'Severe community-acquired pneumonia (CAP)',
    susceptibleTo: ['Ceftriaxone', 'Penicillin G', 'Levofloxacin', 'Vancomycin'],
    resistantTo: ['Macrolides (variable)'],
    micBreakpoints: { Ceftriaxone: 0.5, Penicillin: 0.06 },
    deEscalationOpportunity: 'Immediately narrow from Vancomycin + Cefepime to IV Ceftriaxone 2g daily upon identification.',
  },
]);

export const SEPSIS_EMERGENCY_PROTOCOLS = Object.freeze({
  CODE_SEPSIS: {
    id: 'CODE_SEPSIS',
    label: 'Code Sepsis 1-Hour Activation',
    color: 'rose',
    targetTimeMinutes: 60,
    indications: 'Acute organ dysfunction (SOFA >= 2 or qSOFA >= 2) with suspected infection or initial lactate >= 3.0 mmol/L.',
    actions: [
      'Stat Point-of-Care Blood Lactate & Venous Blood Gas',
      'Two sets of Blood Cultures + Sputum / Urine / Wound cultures',
      'Stat Broad-Spectrum IV Antimicrobial infusion within 60 minutes',
      '30 mL/kg IV Plasmalyte / Lactated Ringers crystalloid bolus',
      'Continuous Arterial Line blood pressure monitoring',
    ],
  },
  REFRACTORY_SEPTIC_SHOCK: {
    id: 'REFRACTORY_SEPTIC_SHOCK',
    label: 'Refractory Shock & Vasopressor Escalation',
    color: 'purple',
    targetTimeMinutes: 30,
    indications: 'Persistent hypotension (MAP < 65 mmHg) despite Norepinephrine > 0.25 mcg/kg/min and fluid loading.',
    actions: [
      'Add second-line Vasopressin at fixed 0.03 units/min infusion (do not titrate)',
      'Consider third-line Epinephrine (0.05-0.2 mcg/kg/min) or Angiotensin II',
      'Initiate Stress-Dose Hydrocortisone 200 mg/day IV continuous infusion',
      'Bedside Critical Care Echocardiography (assess VTI, ejection fraction, RV strain)',
      'Place Central Venous Line (CVC) and evaluate ScvO2 / Central Venous Pressure',
    ],
  },
  ANTIMICROBIAL_STEWARDSHIP_AUDIT: {
    id: 'ANTIMICROBIAL_STEWARDSHIP_AUDIT',
    label: '48-Hour Antimicrobial Time-Out & De-Escalation',
    color: 'cyan',
    targetTimeMinutes: 120,
    indications: 'Microbiology blood culture speciation, viral PCR results, or clinical resolution at 48-72 hours.',
    actions: [
      'Review blood culture gram stain and molecular rapid PCR identification',
      'Discontinue Vancomycin if MRSA PCR / nasal screen / cultures are negative',
      'Narrow spectrum from Meropenem/Cefepime to targeted pathogen monotherapy',
      'Evaluate transition from IV to high-bioavailability Oral therapy',
      'Establish definitive duration of antimicrobial course (5-7 days for most infections)',
    ],
  },
});

export const SEPSIS_PATIENT_FIXTURES = Object.freeze([
  {
    id: 'SEP-PAT-8801',
    mrn: 'MED-908123',
    name: 'Elena Rostova',
    ageYears: 64,
    sex: 'Female',
    location: 'Medical ICU - Bed 04',
    primaryDiagnosis: 'Severe Urosepsis & Septic Shock with Refractory Hypotension',
    suspectedSource: 'Urinary Tract (Indwelling Foley Catheter)',
    severity: 'SEPTIC_SHOCK',
    sofaScore: 9,
    qsofaScore: 3,
    activeProtocol: 'CODE_SEPSIS',
    fluidAdministeredMl: 2200,
    fluidTargetMl: 2100,
    weightKg: 70,
    lactateInitial: 4.8,
    lactateCurrent: 2.9,
    lactateHistory: [4.8, 4.1, 3.5, 2.9],
    procalcitonin: 18.4,
    map: 67,
    systolicBp: 94,
    diastolicBp: 53,
    heartRate: 118,
    respiratoryRate: 26,
    temperatureC: 38.9,
    spo2: 94,
    fio2: 0.45,
    pao2: 82,
    platelets: 98,
    bilirubin: 2.3,
    creatinine: 2.8,
    gcs: 12,
    urineOutputMlPerHr: 22,
    vasopressor: {
      primary: 'Norepinephrine',
      primaryRateMcgKgMin: 0.18,
      secondary: 'Vasopressin',
      secondaryRateUnitsMin: 0.03,
      vasoactiveInotropicScore: 21.0,
    },
    antimicrobialRegimen: [
      {
        drug: 'Meropenem',
        dose: '2g IV q8h (Extended 4h Infusion)',
        startedAtMinutesAgo: 45,
        measuredTrough: 14.2,
        targetTrough: '8 - 16 mcg/mL',
        status: 'OPTIMAL_TARGET',
      },
      {
        drug: 'Vancomycin',
        dose: '1500mg IV Loading, then 1000mg q12h',
        startedAtMinutesAgo: 50,
        measuredTrough: 18.5,
        targetTrough: '15 - 20 mcg/mL',
        estimatedAuc24: 520,
        targetAuc24: '400 - 600',
        status: 'THERAPEUTIC',
      },
    ],
    microbiology: {
      bloodCultures: 'Gram-negative bacilli detected (Gram stain @ 14h)',
      organismPending: 'Klebsiella pneumoniae (Probable ESBL)',
      urineCulture: '> 100,000 CFU/mL Gram-negative rods',
      rapidPcr: 'CTX-M gene detected (+ ESBL)',
    },
    sscBundleProgress: {
      lactateInitialDone: true,
      bloodCulturesDone: true,
      broadAntibioticsDone: true,
      fluidResuscitationDone: true,
      vasopressorsDone: true,
      lactateRepeatDone: true,
    },
  },
  {
    id: 'SEP-PAT-8802',
    mrn: 'MED-745210',
    name: 'Marcus Vance',
    ageYears: 52,
    sex: 'Male',
    location: 'Trauma-Surgical ICU - Bed 09',
    primaryDiagnosis: 'Post-Operative Peritonitis & Polymicrobial Septic Shock',
    suspectedSource: 'Intra-abdominal (Anastomotic Leak)',
    severity: 'REFRACTORY_SHOCK',
    sofaScore: 12,
    qsofaScore: 3,
    activeProtocol: 'REFRACTORY_SEPTIC_SHOCK',
    fluidAdministeredMl: 3000,
    fluidTargetMl: 2550,
    weightKg: 85,
    lactateInitial: 6.2,
    lactateCurrent: 4.6,
    lactateHistory: [6.2, 5.8, 5.1, 4.6],
    procalcitonin: 32.1,
    map: 61,
    systolicBp: 86,
    diastolicBp: 48,
    heartRate: 132,
    respiratoryRate: 30,
    temperatureC: 39.4,
    spo2: 91,
    fio2: 0.60,
    pao2: 74,
    platelets: 65,
    bilirubin: 3.8,
    creatinine: 3.4,
    gcs: 10,
    urineOutputMlPerHr: 14,
    vasopressor: {
      primary: 'Norepinephrine',
      primaryRateMcgKgMin: 0.32,
      secondary: 'Vasopressin',
      secondaryRateUnitsMin: 0.03,
      tertiary: 'Epinephrine',
      tertiaryRateMcgKgMin: 0.08,
      vasoactiveInotropicScore: 48.0,
    },
    antimicrobialRegimen: [
      {
        drug: 'Meropenem',
        dose: '2g IV q8h (Continuous Infusion)',
        startedAtMinutesAgo: 90,
        measuredTrough: 16.8,
        targetTrough: '8 - 16 mcg/mL',
        status: 'THERAPEUTIC',
      },
      {
        drug: 'Colistin',
        dose: '300mg CBA Loading, then 150mg q12h',
        startedAtMinutesAgo: 60,
        measuredTrough: 2.8,
        targetTrough: '2 - 3.5 mcg/mL',
        estimatedAuc24: 58,
        targetAuc24: '>= 50',
        status: 'TARGET_ACHIEVED',
      },
    ],
    microbiology: {
      bloodCultures: '2/2 bottles positive: Gram-negative bacilli & Gram-positive cocci',
      organismPending: 'Pseudomonas aeruginosa + Enterococcus faecium',
      peritonealFluid: 'Polymicrobial anaerobic & aerobic growth',
      rapidPcr: 'VIM Carbapenemase negative, NDM negative',
    },
    sscBundleProgress: {
      lactateInitialDone: true,
      bloodCulturesDone: true,
      broadAntibioticsDone: true,
      fluidResuscitationDone: true,
      vasopressorsDone: true,
      lactateRepeatDone: true,
    },
  },
  {
    id: 'SEP-PAT-8803',
    mrn: 'MED-612984',
    name: 'Gwendolyn Clark',
    ageYears: 71,
    sex: 'Female',
    location: 'Emergency Department - Bay 02',
    primaryDiagnosis: 'Severe Community-Acquired Pneumonia & Impending Sepsis',
    suspectedSource: 'Respiratory (Left Lower Lobe Consolidation)',
    severity: 'SEPSIS',
    sofaScore: 5,
    qsofaScore: 2,
    activeProtocol: 'CODE_SEPSIS',
    fluidAdministeredMl: 1500,
    fluidTargetMl: 1800,
    weightKg: 60,
    lactateInitial: 3.4,
    lactateCurrent: 2.1,
    lactateHistory: [3.4, 2.7, 2.1],
    procalcitonin: 8.9,
    map: 72,
    systolicBp: 104,
    diastolicBp: 56,
    heartRate: 102,
    respiratoryRate: 24,
    temperatureC: 38.6,
    spo2: 93,
    fio2: 0.35,
    pao2: 88,
    platelets: 175,
    bilirubin: 0.9,
    creatinine: 1.5,
    gcs: 14,
    urineOutputMlPerHr: 45,
    vasopressor: {
      primary: 'None (Fluid responsive)',
      primaryRateMcgKgMin: 0.0,
      secondary: 'None',
      secondaryRateUnitsMin: 0.0,
      vasoactiveInotropicScore: 0.0,
    },
    antimicrobialRegimen: [
      {
        drug: 'Ceftriaxone',
        dose: '2g IV q24h',
        startedAtMinutesAgo: 35,
        measuredTrough: 22.0,
        targetTrough: '10 - 30 mcg/mL',
        status: 'THERAPEUTIC',
      },
      {
        drug: 'Azithromycin',
        dose: '500mg IV q24h',
        startedAtMinutesAgo: 40,
        measuredTrough: 0.8,
        targetTrough: '0.4 - 1.0 mcg/mL',
        status: 'THERAPEUTIC',
      },
    ],
    microbiology: {
      bloodCultures: 'Preliminary Gram stain: Gram-positive lancet-shaped diplococci',
      organismPending: 'Streptococcus pneumoniae (Pneumococcus)',
      urinaryAntigen: 'Positive for S. pneumoniae antigen',
      sputumPcr: 'High-load Streptococcus pneumoniae detected',
    },
    sscBundleProgress: {
      lactateInitialDone: true,
      bloodCulturesDone: true,
      broadAntibioticsDone: true,
      fluidResuscitationDone: true,
      vasopressorsDone: false,
      lactateRepeatDone: true,
    },
  },
]);
