/**
 * Trauma Resuscitation, Massive Transfusion Protocol (MTP) & Damage Control Models
 * Adheres to American College of Surgeons Trauma Quality Improvement Program (ACS-TQIP),
 * Eastern Association for the Surgery of Trauma (EAST) Damage Control Resuscitation Guidelines,
 * CRASH-2 / CRASH-3 Tranexamic Acid Protocols, and FDA 21 CFR Part 11 Audit Integrity.
 */

export const TEG_ROTEM_THRESHOLDS = {
  R_TIME_CLOTTING_FACTORS: {
    id: "R_TIME",
    name: "Reaction Time (R-Time)",
    unit: "min",
    normalRange: [4.0, 8.0],
    abnormalProlonged: 8.0, // Indicates clotting factor deficiency
    guidedComponent: "Fresh Frozen Plasma (FFP) or Prothrombin Complex Concentrate (PCC)",
  },
  K_TIME_FIBRINOGEN: {
    id: "K_TIME",
    name: "Kinetics Time (K-Time)",
    unit: "min",
    normalRange: [1.0, 3.0],
    abnormalProlonged: 3.0,
    guidedComponent: "Cryoprecipitate / Fibrinogen Concentrate",
  },
  ALPHA_ANGLE_POLYMERIZATION: {
    id: "ALPHA_ANGLE",
    name: "Alpha Angle (Fibrinogen Crosslinking)",
    unit: "degrees",
    normalRange: [60.0, 78.0],
    abnormalLow: 60.0,
    guidedComponent: "Cryoprecipitate (Target Fibrinogen > 150-200 mg/dL)",
  },
  MAXIMUM_AMPLITUDE_PLATELETS: {
    id: "MAXIMUM_AMPLITUDE",
    name: "Maximum Amplitude (MA - Clot Strength)",
    unit: "mm",
    normalRange: [52.0, 72.0],
    abnormalLow: 52.0, // Indicates platelet dysfunction or severe thrombocytopenia
    guidedComponent: "Platelet Apheresis Unit / DDAVP",
  },
  LY30_HYPERFIBRINOLYSIS: {
    id: "LY30",
    name: "Clot Lysis at 30 min (LY30)",
    unit: "%",
    normalRange: [0.0, 3.0],
    criticalHyperfibrinolysis: 3.0, // Indicates systemic fibrinolysis
    guidedComponent: "Tranexamic Acid (TXA 1g IV loading over 10 min, then 1g over 8 hr)",
  },
};

export const MTP_COOLER_PACKS = {
  ROUND_1: {
    packId: "MTP-PACK-01",
    name: "Initial MTP Emergency Pack (Cooler 1)",
    components: {
      prbcUnits: 4,
      ffpUnits: 4,
      plateletApharesisUnits: 1, // Equivalent to 6 whole blood platelet units
      cryoprecipitatePools: 0,
      txaGrams: 1.0,
    },
    ratio: "1:1:1 Balanced Whole Blood Equivalence",
  },
  ROUND_2: {
    packId: "MTP-PACK-02",
    name: "Sustained Resuscitation Pack (Cooler 2)",
    components: {
      prbcUnits: 4,
      ffpUnits: 4,
      plateletApharesisUnits: 1,
      cryoprecipitatePools: 2, // 10-20 units total
      calciumChlorideGrams: 1.0,
    },
    ratio: "1:1:1 + Fibrinogen & Calcium Restoration",
  },
};

export const DAMAGE_CONTROL_TARGETS = {
  PERMISSIVE_HYPOTENSION: {
    targetSbpMmHg: [80, 90], // Prior to definitive surgical hemostasis in blunt/penetrating torso trauma
    targetMapMmHg: [50, 65],
    contraindication: "Severe Traumatic Brain Injury (TBI requires MAP >= 80 to prevent secondary ischemia)",
  },
  BODY_CORE_TEMPERATURE: {
    targetMinC: 36.0,
    criticalLethalTriadC: 35.0, // Hypothermia induces coagulopathy and platelet dysfunction
  },
  SERUM_LACTATE_BASE_DEFICIT: {
    lactateNormalMmol: [0.5, 2.0],
    lactateSevereShockMmol: 4.0,
    baseDeficitNormalMeq: [-2.0, 2.0],
    baseDeficitSevereMeq: -6.0,
  },
  IONIZED_CALCIUM: {
    unit: "mmol/L",
    normalMin: 1.15,
    criticalCitrateToxicityMin: 0.9, // Citrate anticoagulant in blood products binds ionized Ca2+
  },
};

export const EMERGENCY_TRAUMA_PROTOCOLS = {
  MTP_ACTIVATION: {
    id: "MTP_ACTIVATION",
    title: "Code Massive Transfusion Protocol (MTP)",
    severity: "CRITICAL_EXSANGUINATION",
    triggerCriteria: "ABC Score >= 2 OR Shock Index > 1.0 OR active uncontrollable cavitary hemorrhage",
    actions: [
      "Activate Hospital-Wide Massive Transfusion Protocol via Blood Bank STAT.",
      "Deploy Cooler 1 (4 PRBC : 4 FFP : 1 Platelet Apheresis) to Trauma Bay immediately.",
      "Administer IV Tranexamic Acid (TXA) 1g bolus within 3 hours of trauma onset.",
      "Prime Rapid Infuser (Belmont/Level 1) with fluid warmer set to 41.0°C.",
      "Check Ionized Calcium every 4 units of blood; administer 1g Calcium Chloride for Ca < 1.15 mmol/L.",
      "Send baseline TEG 6s, ABG with Lactate, CBC, and Coagulation panel stat.",
    ],
  },
  REBOA_DEPLOYMENT: {
    id: "REBOA_DEPLOYMENT",
    title: "Code REBOA (Resuscitative Endovascular Balloon Occlusion)",
    severity: "HIGH_RISK_SURGICAL_BRIDGE",
    triggerCriteria: "Subdiaphragmatic exsanguination with PEA arrest or SBP < 70 refractory to initial infusion",
    actions: [
      "Percutaneous ultrasound-guided common femoral arterial sheath placement (5-7 Fr).",
      "Advance REBOA balloon catheter into Zone I (descending thoracic aorta) or Zone III (distal abdominal aorta).",
      "Inflate balloon with radiopaque contrast-saline mixture until aortic pulse occlusion confirmed.",
      "Strict balloon occlusion timer: Limit total continuous Zone I occlusion to < 30 minutes to prevent visceral ischemia.",
      "Proceed emergently to Operating Room for damage control laparotomy / pelvic preperitoneal packing.",
    ],
  },
  DAMAGE_CONTROL_SURGERY: {
    id: "DAMAGE_CONTROL_SURGERY",
    title: "Code Damage Control Laparotomy / Sternotomy",
    severity: "SURGICAL_EMERGENCY",
    triggerCriteria: "Trauma Lethal Triad (Hypothermia < 35°C, Acidosis pH < 7.20, Coagulopathy INR > 1.5)",
    actions: [
      "Abort complex anatomic reconstructions; perform rapid 4-quadrant surgical packing.",
      "Control enteric contamination with rapid stapling and temporary vascular shunts.",
      "Apply negative pressure temporary abdominal closure (Abthera / Bogota bag).",
      "Transfer to Surgical ICU for core rewarming, MTP resuscitation, and correction of coagulopathy.",
    ],
  },
};

export const INITIAL_TRAUMA_PATIENTS = [
  {
    id: "PT-TRAUMA-7701",
    name: "Captain Zachary Vance",
    mrn: "MRN-5519401",
    age: 29,
    gender: "Male",
    weightKg: 78,
    heightCm: 180,
    injuryMechanism: "High-Velocity Motor Vehicle Collision with Steering Wheel Crush Injury",
    injurySeverityScore: 34,
    admissionDate: "2026-08-22T19:30:00Z",
    minutesFromInjury: 42,
    heartRateBpm: 138,
    systolicBpMmHg: 76,
    diastolicBpMmHg: 44,
    meanArterialPressureMmHg: 54.7,
    shockIndex: 1.82,
    respiratoryRateBpm: 28,
    spO2Percent: 92.0,
    coreTemperatureC: 35.4,
    abcScore: 3, // Penetrating: 0, SBP<=90: 1, HR>=120: 1, FAST+: 1
    fastUltrasoundMorisonPouch: "POSITIVE_FREE_FLUID",
    fastUltrasoundSplenorenal: "POSITIVE_FREE_FLUID",
    fastUltrasoundPelvis: "POSITIVE_FREE_FLUID",
    fastUltrasoundPericardial: "NEGATIVE",
    tegRTimeMin: 10.4, // Prolonged -> FFP needed
    tegKTimeMin: 4.2,
    tegAlphaAngleDeg: 52.0, // Low -> Cryoprecipitate needed
    tegMaximumAmplitudeMm: 44.0, // Low -> Platelets needed
    tegLy30Percent: 6.8, // Critical Hyperfibrinolysis -> TXA needed
    prbcUnitsTransfused: 6,
    ffpUnitsTransfused: 4,
    plateletUnitsTransfused: 1,
    cryoUnitsTransfused: 0,
    txaAdministeredGrams: 1.0,
    rapidInfuserRateMlMin: 450,
    rapidInfuserTotalVolumeMl: 2850,
    rapidInfuserLinePressureMmHg: 180,
    rapidInfuserWarmerTempC: 40.5,
    arterialPh: 7.18,
    arterialLactateMmol: 6.4,
    baseDeficitMeqL: -9.2,
    hemoglobinGdl: 7.2,
    plateletsPerUl: 68000,
    ionizedCalciumMmolL: 0.94, // Citrate binding -> IV Calcium needed
    fibrinogenMgDl: 110,
    reboaStatus: "ZONE_I_INFLATED",
    reboaOcclusionMinutes: 14.5,
    surgicalStatus: "OR_DAMAGE_CONTROL_STANDBY",
    clinicalStatus: "CRITICAL_EXSANGUINATING_SHOCK_MTP_ACTIVE",
  },
  {
    id: "PT-TRAUMA-7702",
    name: "Sergeant Maya Lin",
    mrn: "MRN-6628104",
    age: 34,
    gender: "Female",
    weightKg: 62,
    heightCm: 168,
    injuryMechanism: "Multiple Gunshot Wounds to Right Thoraco-Abdominal Cavity",
    injurySeverityScore: 29,
    admissionDate: "2026-08-22T20:10:00Z",
    minutesFromInjury: 28,
    heartRateBpm: 122,
    systolicBpMmHg: 88,
    diastolicBpMmHg: 52,
    meanArterialPressureMmHg: 64.0,
    shockIndex: 1.39,
    respiratoryRateBpm: 24,
    spO2Percent: 96.0,
    coreTemperatureC: 36.2,
    abcScore: 3, // Penetrating: 1, SBP<=90: 1, HR>=120: 1, FAST+: 0
    fastUltrasoundMorisonPouch: "NEGATIVE",
    fastUltrasoundSplenorenal: "NEGATIVE",
    fastUltrasoundPelvis: "NEGATIVE",
    fastUltrasoundPericardial: "NEGATIVE",
    tegRTimeMin: 6.2,
    tegKTimeMin: 2.1,
    tegAlphaAngleDeg: 66.0,
    tegMaximumAmplitudeMm: 58.0,
    tegLy30Percent: 1.8,
    prbcUnitsTransfused: 2,
    ffpUnitsTransfused: 2,
    plateletUnitsTransfused: 0,
    cryoUnitsTransfused: 0,
    txaAdministeredGrams: 1.0,
    rapidInfuserRateMlMin: 200,
    rapidInfuserTotalVolumeMl: 1100,
    rapidInfuserLinePressureMmHg: 120,
    rapidInfuserWarmerTempC: 40.0,
    arterialPh: 7.31,
    arterialLactateMmol: 3.8,
    baseDeficitMeqL: -4.5,
    hemoglobinGdl: 9.6,
    plateletsPerUl: 142000,
    ionizedCalciumMmolL: 1.12,
    fibrinogenMgDl: 185,
    reboaStatus: "NOT_DEPLOYED",
    reboaOcclusionMinutes: 0,
    surgicalStatus: "EXPLORATORY_LAPAROTOMY_ACTIVE",
    clinicalStatus: "MODERATE_HEMORRHAGIC_SHOCK_CONTROLLED",
  },
  {
    id: "PT-TRAUMA-7703",
    name: "Arthur Pendelton, EMT-P",
    mrn: "MRN-4491028",
    age: 48,
    gender: "Male",
    weightKg: 86,
    heightCm: 175,
    injuryMechanism: "Pedestrian vs Industrial Heavy Forklift - Open Pelvic Fracture",
    injurySeverityScore: 41,
    admissionDate: "2026-08-22T18:45:00Z",
    minutesFromInjury: 85,
    heartRateBpm: 110,
    systolicBpMmHg: 96,
    diastolicBpMmHg: 60,
    meanArterialPressureMmHg: 72.0,
    shockIndex: 1.15,
    respiratoryRateBpm: 18,
    spO2Percent: 98.0,
    coreTemperatureC: 36.8,
    abcScore: 2, // Penetrating: 0, SBP<=90: 0, HR>=120: 0, Pelvis/FAST+: 2
    fastUltrasoundMorisonPouch: "NEGATIVE",
    fastUltrasoundSplenorenal: "NEGATIVE",
    fastUltrasoundPelvis: "POSITIVE_RETROPERITONEAL_HEMATOMA",
    fastUltrasoundPericardial: "NEGATIVE",
    tegRTimeMin: 7.0,
    tegKTimeMin: 1.8,
    tegAlphaAngleDeg: 71.0,
    tegMaximumAmplitudeMm: 62.0,
    tegLy30Percent: 0.9,
    prbcUnitsTransfused: 8,
    ffpUnitsTransfused: 8,
    plateletUnitsTransfused: 2,
    cryoUnitsTransfused: 2,
    txaAdministeredGrams: 2.0,
    rapidInfuserRateMlMin: 50,
    rapidInfuserTotalVolumeMl: 4600,
    rapidInfuserLinePressureMmHg: 90,
    rapidInfuserWarmerTempC: 39.5,
    arterialPh: 7.36,
    arterialLactateMmol: 2.1,
    baseDeficitMeqL: -2.0,
    hemoglobinGdl: 10.4,
    plateletsPerUl: 165000,
    ionizedCalciumMmolL: 1.21,
    fibrinogenMgDl: 220,
    reboaStatus: "ZONE_III_DEFLATED",
    reboaOcclusionMinutes: 22.0,
    surgicalStatus: "PELVIC_ANGIOEMBOLIZATION_COMPLETE",
    clinicalStatus: "RESUSCITATED_POST_PACKING_STABILIZED",
  },
];
