const { workerData, parentPort } = require("worker_threads");
const PDFDocument = require("pdfkit");
const { formatCurrency } = require("../utils/currency");

async function generatePDF() {
  try {
    const { type, payload } = workerData;

    if (type === "GENERATE_COMPANY_REPORT") {
      const { payrolls, employeeMap, companyName, companyLogo, monthName, year, totalBase, totalOvertime, totalBonus, totalDeductions, totalPayout, currency = "INR" } = payload;
      
      const doc = new PDFDocument({ size: "A4", margin: 40, bufferPages: true });
      const buffers = [];
      doc.on("data", buffers.push.bind(buffers));
      doc.on("end", () => {
        const pdfData = Buffer.concat(buffers);
        parentPort.postMessage({ success: true, pdfData });
      });

      // --- Company Header ---
      if (companyLogo) {
        try {
          // companyLogo might be a base64 string
          const logoBuffer = Buffer.from(companyLogo.replace(/^data:image\/\w+;base64,/, ""), 'base64');
          doc.image(logoBuffer, 40, 30, { fit: [50, 50] });
        } catch (error) { console.error(error); }
      }
      doc.fontSize(22).font("Helvetica-Bold").fillColor("#1e3a5f").text(companyName, { align: "center" });
      doc.fontSize(12).font("Helvetica").fillColor("#666666").text(`Payroll Summary Report — ${monthName} ${year}`, { align: "center" });
      doc.moveDown(0.5);

      // Divider line
      doc.moveTo(40, doc.y).lineTo(555, doc.y).strokeColor("#cccccc").lineWidth(1).stroke();
      doc.moveDown(1);

      // --- Summary Section ---
      doc.fontSize(14).font("Helvetica-Bold").fillColor("#333333").text("Financial Summary");
      doc.moveDown(0.3);

      const summaryData = [
        ["Total Employees", String(payrolls.length)],
        ["Total Base Salary", formatCurrency(totalBase, currency)],
        ["Total Overtime Pay", formatCurrency(totalOvertime, currency)],
        ["Total Bonuses", formatCurrency(totalBonus, currency)],
        ["Total Deductions", formatCurrency(totalDeductions, currency)],
        ["Net Payout", formatCurrency(totalPayout, currency)],
      ];


    summaryData.forEach(([label, value]) => {
      doc
        .fontSize(10)
        .font("Helvetica")
        .fillColor("#555555")
        .text(label, 60, doc.y, { continued: true, width: 200 });
      doc
        .font("Helvetica-Bold")
        .fillColor("#1e3a5f")
        .text(`  ${value}`, { align: "right" });
      doc.moveDown(0.2);
    });

    doc.moveDown(1);

    // --- Employee Payroll Table ---
    doc
      .fontSize(14)
      .font("Helvetica-Bold")
      .fillColor("#333333")
      .text("Employee Payroll Details");

    doc.moveDown(0.5);

    // Table header
    const tableTop = doc.y;
    const colWidths = [110, 65, 55, 60, 55, 55, 65];
    const colLabels = [
      "Employee",
      "Base",
      "Leave",
      "Overtime",
      "Bonus",
      "Deduct",
      "Net Pay",
    ];
    const startX = 40;

    // Header background
    doc
      .rect(startX, tableTop - 4, 515, 18)
      .fill("#e8edf3");

    let xPos = startX + 5;
    colLabels.forEach((label, i) => {
      doc
        .fontSize(8)
        .font("Helvetica-Bold")
        .fillColor("#333333")
        .text(label, xPos, tableTop, { width: colWidths[i] });
      xPos += colWidths[i];
    });

    doc.y = tableTop + 18;

    // Table rows
    payrolls.forEach((p, idx) => {
      if (doc.y > 750) {
        doc.addPage();
      }

      const rowY = doc.y;
      const emp = employeeMap[String(p.employeeId)];
      const role = emp?.role ? ` (${emp.role})` : "";

      // Alternating row background
      if (idx % 2 === 0) {
        doc.rect(startX, rowY - 2, 515, 14).fill("#f9fafb");
      }

      const rowData = [
        `${p.employeeName}${role}`,
        formatCurrency(p.baseSalary, currency),
        String(p.leaveDays),
        formatCurrency(p.overtimePay, currency),
        formatCurrency(p.bonus, currency),
        formatCurrency(p.deductions + p.leaveDeduction, currency),
        formatCurrency(p.netSalary, currency),
      ];

      xPos = startX + 5;
      rowData.forEach((cell, i) => {
        doc
          .fontSize(8)
          .font("Helvetica")
          .fillColor("#444444")
          .text(cell, xPos, rowY, { width: colWidths[i] });
        xPos += colWidths[i];
      });

      doc.y = rowY + 14;
      });

      doc.moveDown(0.5);
      doc.moveTo(startX, doc.y).lineTo(startX + 515, doc.y).strokeColor("#cccccc").lineWidth(0.5).stroke();
      doc.moveDown(0.3);
      doc.fontSize(9).font("Helvetica-Bold").fillColor("#1e3a5f").text(`Total Payout: ${formatCurrency(totalPayout, currency)}`, startX, doc.y, { align: "right" });

      const pageCount = doc.bufferedPageRange().count;
      for (let i = 0; i < pageCount; i++) {
        doc.switchToPage(i);
        doc.fontSize(8).font("Helvetica").fillColor("#aaaaaa").text(`Generated by PaySphere • Page ${i + 1} of ${pageCount}`, 40, doc.page.height - 30, { align: "center", width: 515 });
      }

      doc.end();

    } else if (type === "GENERATE_PAYSLIP") {
      const { employee, payroll, companyLogo, currency = "INR" } = payload;
      
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];
      doc.on("data", buffers.push.bind(buffers));
      doc.on("end", () => {
        const pdfData = Buffer.concat(buffers);
        parentPort.postMessage({ success: true, pdfData });
      });

      // Build PDF content
      if (companyLogo) {
        try {
          const logoBuffer = Buffer.from(companyLogo.replace(/^data:image\/\w+;base64,/, ""), 'base64');
          doc.image(logoBuffer, 50, 40, { fit: [50, 50] });
        } catch (error) { console.error(error); }
      }
      doc.fontSize(20).text("PaySphere", { align: "center" });
      doc.moveDown();
      doc.fontSize(16).text(`Payslip for ${payroll.month}/${payroll.year}`, { align: "center" });
      doc.moveDown(2);

      doc.fontSize(12).text(`Employee Name: ${employee.fullName}`);
      doc.text(`Role: ${employee.role || "N/A"}`);
      doc.text(`Company: ${employee.companyName}`);
      doc.moveDown();

      doc.text(`Base Salary: ${formatCurrency(payroll.baseSalary, currency)}`);
      doc.text(`Leave Days: ${payroll.leaveDays} (-${formatCurrency(payroll.leaveDeduction, currency)})`);
      doc.text(`Overtime Hours: ${payroll.overtimeHours} (+${formatCurrency(payroll.overtimePay, currency)})`);
      doc.text(`Bonus: +${formatCurrency(payroll.bonus, currency)}`);
      doc.text(`Deductions: -${formatCurrency(payroll.deductions, currency)}`);
      doc.moveDown();

      doc.fontSize(14).text(`Net Salary: ${formatCurrency(payroll.netSalary, currency)}`, { underline: true });
      doc.end();
    }

    doc.end();
  } catch (error) {
    parentPort.postMessage({ success: false, error: error.message });
  }
}

generatePDF();
