/**
 * Garnishment Legal Compliance Constant Definitions
 */

export const GARNISHMENT_LEGAL_CONSTANTS = {
  CCPA_CAP_SECOND_FAMILY_NO_ARREARS: 0.50,
  CCPA_CAP_SECOND_FAMILY_WITH_ARREARS: 0.55,
  CCPA_CAP_NO_SECOND_FAMILY_NO_ARREARS: 0.60,
  CCPA_CAP_NO_SECOND_FAMILY_WITH_ARREARS: 0.65,
  CCPA_CREDITOR_GARNISHMENT_CAP: 0.25,
  FEDERAL_MINIMUM_WAGE_HOURLY: 7.25
};
